label values ra_instruct ra_instruct_
label values attempt attempt_
label values ra_instruct_1stattempt ra_instruct_1stattempt_
label values ra_instruct_2nd_3rdattempt ra_instruct_2nd_3rdattempt_
label values hhl_complete hhl_complete_
label values area_1 area_1_
label values study_community_1 study_community_1_
label values square_number_1 square_number_1_
label values sub_square_letter_1 sub_square_letter_1_
label values confirm_infrontofgate_door_1 confirm_infrontofgate_door_1_
label values hhmember_present_1 hhmember_present_1_
label values hh_not_present_confirm_1 hh_not_present_confirm_1_
label values intro_script1_1 intro_script1_1_
label values hoh_at_home_1 hoh_at_home_1_
label values intro_script_2_1 intro_script_2_1_
label values interest_status_1 interest_status_1_
label values area_2 area_2_
label values study_community_2 study_community_2_
label values square_number_2 square_number_2_
label values sub_square_letter_2 sub_square_letter_2_
label values confirm_infrontofgate_door_2 confirm_infrontofgate_door_2_
label values hhmember_present_2 hhmember_present_2_
label values hh_not_present_confirm_2 hh_not_present_confirm_2_
label values intro_script1_2 intro_script1_2_
label values hoh_at_home_2 hoh_at_home_2_
label values intro_script_2_2 intro_script_2_2_
label values interest_status_2 interest_status_2_
label values area_3 area_3_
label values study_community_3 study_community_3_
label values square_number_3 square_number_3_
label values sub_square_letter_3 sub_square_letter_3_
label values confirm_infrontofgate_door_3 confirm_infrontofgate_door_3_
label values hhmember_present_3 hhmember_present_3_
label values hh_not_present_confirm_3 hh_not_present_confirm_3_
label values intro_script1_3 intro_script1_3_
label values hoh_at_home_3 hoh_at_home_3_
label values intro_script_2_3 intro_script_2_3_
label values interest_status_3 interest_status_3_
label values screening_for_eligibility screening_for_eligibility_
label values participant_gender participant_gender_
label values lang_fluent lang_fluent_
label values community community_
label values ra_the_participant_is_elig ra_the_participant_is_elig_
label values ra_the_person_is_not_eligi ra_the_person_is_not_eligi_
label values note_to_ra_you_will_now_st note_to_ra_you_will_now_st_
label values preferred_language_to_be_u preferred_language_to_be_u_
label values did_the_person_consent_to did_the_person_consent_to_
label values participant_can_sign participant_can_sign_
label values refconfirm refconfirm_
label values consented_the_person_has_a consented_the_person_has_a_
label values pin_display pin_display_
label values consent_qc_1 consent_qc_1_
label values consent_qc_2 consent_qc_2_
label values consent_qc_3 consent_qc_3_
label values contact_no_2 contact_no_2_
label values sc_complete screening_and_consen_v_1_
label values language_prefer language_prefer_
label values other_studies other_studies_
label values other_studies_time_e other_studies_time_e_
label values s1_q1 s1_q1_
label values place_of_birth_rsa_e place_of_birth_rsa_e_
label values place_of_birth_other place_of_birth_other_
label values s1_q5 s1_q5_
label values living_arrangement_e living_arrangement_e_
label values s1_q6 s1_q6_
label values s1_q7 s1_q7_
label values s1_q14 s1_q14_
label values s2_q2 s2_q2_
label values hoh_tb_hist_clinic hoh_tb_hist_clinic_
label values hhm_tb_e hhm_tb_e_
label values hhm_tb_hist_clinic hhm_tb_hist_clinic_
label values s2_q3 s2_q3_
label values s2_q5 s2_q5_
label values hh_member_hiv hh_member_hiv_
label values s2_q9 s2_q9_
label values s5_q1___1 s5_q1___1_
label values s5_q1___2 s5_q1___2_
label values s5_q1___3 s5_q1___3_
label values s5_q1___4 s5_q1___4_
label values s5_q1___5 s5_q1___5_
label values s5_q1___6 s5_q1___6_
label values s5_q1___7 s5_q1___7_
label values s5_q1___8 s5_q1___8_
label values s5_q1___9 s5_q1___9_
label values s5_q2___1 s5_q2___1_
label values s5_q2___2 s5_q2___2_
label values s5_q2___3 s5_q2___3_
label values s5_q2___4 s5_q2___4_
label values s5_q2___5 s5_q2___5_
label values s5_q2___6 s5_q2___6_
label values s5_q2___7 s5_q2___7_
label values s5_q3___1 s5_q3___1_
label values s5_q3___2 s5_q3___2_
label values s5_q3___3 s5_q3___3_
label values s5_q3___4 s5_q3___4_
label values s5_q3___5 s5_q3___5_
label values s5_q3___6 s5_q3___6_
label values s5_q3___7 s5_q3___7_
label values s5_q3___8 s5_q3___8_
label values s5_q3___9 s5_q3___9_
label values s5_q3___10 s5_q3___10_
label values s5_q3___11 s5_q3___11_
label values s5_q4 s5_q4_
label values s5_q5 s5_q5_
label values mental_health_history_e___1 mental_health_history_e___1_
label values mental_health_history_e___2 mental_health_history_e___2_
label values mental_health_history_e___3 mental_health_history_e___3_
label values mental_health_history_e___4 mental_health_history_e___4_
label values mental_health_history_e___5 mental_health_history_e___5_
label values mental_health_history_e___6 mental_health_history_e___6_
label values mental_health_history_e___7 mental_health_history_e___7_
label values mental_health_history_e___8 mental_health_history_e___8_
label values mental_health_history_e___9 mental_health_history_e___9_
label values mental_health_history_e___10 mental_health_history_e___10_
label values mental_health_history_e___11 mental_health_history_e___11_
label values mental_health_history2_e mental_health_history2_e_
label values fam_mental_health1_e fam_mental_health1_e_
label values fam_mental_health2_e fam_mental_health2_e_
label values gender_hhm_1 gender_hhm_1_
label values gender_hhm_2 gender_hhm_2_
label values gender_hhm_3 gender_hhm_3_
label values gender_hhm_4 gender_hhm_4_
label values gender_hhm_5 gender_hhm_5_
label values gender_hhm_6 gender_hhm_6_
label values gender_hhm_7 gender_hhm_7_
label values gender_hhm_8 gender_hhm_8_
label values gender_hhm_9 gender_hhm_9_
label values gender_hhm_10 gender_hhm_10_
label values gender_hhm_11 gender_hhm_11_
label values gender_hhm_12 gender_hhm_12_
label values gender_hhm_13 gender_hhm_13_
label values gender_hhm_14 gender_hhm_14_
label values gender_hhm_15 gender_hhm_15_
label values age6to13_confirm age6to13_confirm_
label values highest_education highest_education_
label values highest_primary highest_primary_
label values highest_grade_ofall highest_grade_ofall_
label values highest_primary_ofall highest_primary_ofall_
label values attend_school attend_school_
label values highest_grade_notattending highest_grade_notattending_
label values child_mortality child_mortality_
label values drinking_water_e drinking_water_e_
label values water_located_e water_located_e_
label values toilet_e toilet_e_
label values fuel_e fuel_e_
label values cooking_place_e cooking_place_e_
label values seperate_cook_space_e seperate_cook_space_e_
label values mains_elec_e mains_elec_e_
label values asset1 asset1_
label values asset2 asset2_
label values asset3 asset3_
label values asset4 asset4_
label values asset5 asset5_
label values asset6 asset6_
label values asset7 asset7_
label values asset8 asset8_
label values asset9 asset9_
label values own1 own1_
label values own2 own2_
label values own3 own3_
label values own4 own4_
label values own5 own5_
label values own6 own6_
label values own7 own7_
label values floor floor_
label values roof roof_
label values fam_decision_1 fam_decision_1_
label values fam_decision_2 fam_decision_2_
label values fam_decision_3 fam_decision_3_
label values navigate_tablet_e navigate_tablet_e_
label values ra_note_e ra_note_e_
label values literate_check_e literate_check_e_
label values f1 f1_
label values f2 f2_
label values f3 f3_
label values fun1___1 fun1___1_
label values fun1___2 fun1___2_
label values fun1___3 fun1___3_
label values fun1___4 fun1___4_
label values fun1___5 fun1___5_
label values fun1___6 fun1___6_
label values fun2 fun2_
label values instruct_part instruct_part_
label values hhd_complete hhd_complete_
label values ques_language ques_language_
label values hoh_last_clinic_any_e hoh_last_clinic_any_e_
label values symptom_preffered_clinic symptom_preffered_clinic_
label values tb_diagnosed_clinic_prefer tb_diagnosed_clinic_prefer_
label values hiv_clinic_prefer_test hiv_clinic_prefer_test_
label values hiv_clinic_prefer_treat hiv_clinic_prefer_treat_
label values non_tb_care_util non_tb_care_util_
label values type_health_util___1 type_health_util___1_
label values type_health_util___2 type_health_util___2_
label values type_health_util___3 type_health_util___3_
label values type_health_util___4 type_health_util___4_
label values prison prison_
label values prison_time prison_time_
label values prison_release prison_release_
label values mines mines_
label values mines_time mines_time_
label values mines_long_ago mines_long_ago_
label values ss1 ss1_
label values ss2 ss2_
label values ss3 ss3_
label values ss4 ss4_
label values ss5 ss5_
label values ss6 ss6_
label values ss7 ss7_
label values ss8 ss8_
label values ss9 ss9_
label values ss10 ss10_
label values ss11 ss11_
label values ss12 ss12_
label values e1_eng e1_eng_
label values e2_eng e2_eng_
label values e3_eng e3_eng_
label values e4_eng e4_eng_
label values e5_eng e5_eng_
label values e6_eng e6_eng_
label values e7_eng e7_eng_
label values e8_eng e8_eng_
label values e9_eng e9_eng_
label values e10_eng e10_eng_
label values e11_eng e11_eng_
label values e12_eng e12_eng_
label values e13_eng e13_eng_
label values e14_eng e14_eng_
label values e15_eng e15_eng_
label values e16_eng e16_eng_
label values e17_eng e17_eng_
label values e18_eng e18_eng_
label values e21_eng e21_eng_
label values e22_eng e22_eng_
label values e23_eng e23_eng_
label values e24_eng e24_eng_
label values e25_eng e25_eng_
label values e26_eng e26_eng_
label values e27_eng e27_eng_
label values e28_eng e28_eng_
label values e29_eng e29_eng_
label values e30_eng e30_eng_
label values rights_equity_1 rights_equity_1_
label values rights_equity_2 rights_equity_2_
label values rights_equity_3 rights_equity_3_
label values rights_equity_4 rights_equity_4_
label values rights_equity_5 rights_equity_5_
label values rights_equity_6 rights_equity_6_
label values rights_equity_7 rights_equity_7_
label values rights_equity_8 rights_equity_8_
label values rights_equity_9 rights_equity_9_
label values rights_equity_10 rights_equity_10_
label values rights_equity_11 rights_equity_11_
label values rights_equity_12 rights_equity_12_
label values rights_equity_13 rights_equity_13_
label values rights_equity_14 rights_equity_14_
label values gender_norms_1 gender_norms_1_
label values gender_norms_2 gender_norms_2_
label values gender_norms_3 gender_norms_3_
label values gender_norms_4 gender_norms_4_
label values gender_norms_5 gender_norms_5_
label values gender_norms_6 gender_norms_6_
label values gender_norms_7 gender_norms_7_
label values gender_norms_8 gender_norms_8_
label values gender_norms_9 gender_norms_9_
label values gender_norms_10 gender_norms_10_
label values gender_norms_11 gender_norms_11_
label values gender_norms_12 gender_norms_12_
label values gender_norms_13 gender_norms_13_
label values gender_norms_14 gender_norms_14_
label values gender_norms_15 gender_norms_15_
label values gender_norms_16 gender_norms_16_
label values gender_norms_17 gender_norms_17_
label values gender_role_1 gender_role_1_
label values gender_role_2 gender_role_2_
label values gender_role_3 gender_role_3_
label values gender_role_4 gender_role_4_
label values gender_role_5 gender_role_5_
label values gender_role_6 gender_role_6_
label values gender_role_7 gender_role_7_
label values gender_role_8 gender_role_8_
label values gender_role_9 gender_role_9_
label values gender_role_10 gender_role_10_
label values gender_role_11 gender_role_11_
label values gender_role_12 gender_role_12_
label values gender_role_13 gender_role_13_
label values gender_role_14 gender_role_14_
label values gender_role_15 gender_role_15_
label values gender_role_16 gender_role_16_
label values gender_role_17 gender_role_17_
label values gender_role_18 gender_role_18_
label values gender_role_19 gender_role_19_
label values gender_role_20 gender_role_20_
label values gender_role_21 gender_role_21_
label values gender_role_22 gender_role_22_
label values gender_role_23 gender_role_23_
label values gender_role_24 gender_role_24_
label values masc_chronic_d1 masc_chronic_d1_
label values masc_chronic_d2 masc_chronic_d2_
label values masc_chronic_d3 masc_chronic_d3_
label values masc_chronic_d4 masc_chronic_d4_
label values masc_chronic_d5 masc_chronic_d5_
label values masc_chronic_d6 masc_chronic_d6_
label values masc_chronic_d7 masc_chronic_d7_
label values masc_chronic_d8 masc_chronic_d8_
label values masc_chronic_d9 masc_chronic_d9_
label values c1_eng c1_eng_
label values c2_eng c2_eng_
label values c3_eng c3_eng_
label values c4_eng c4_eng_
label values c4a_eng c4a_eng_
label values c5_eng c5_eng_
label values c6_eng c6_eng_
label values c7_eng c7_eng_
label values c8_eng c8_eng_
label values c8a_eng c8a_eng_
label values c_child_age c_child_age_
label values c9_eng c9_eng_
label values c10_eng c10_eng_
label values c11_eng c11_eng_
label values c12_eng c12_eng_
label values c13_eng c13_eng_
label values c13a_eng c13a_eng_
label values c14_eng c14_eng_
label values c15_eng c15_eng_
label values d1_eng d1_eng_
label values d2_eng d2_eng_
label values d3_eng d3_eng_
label values d4_eng d4_eng_
label values d5_eng d5_eng_
label values d6_eng d6_eng_
label values d7_eng d7_eng_
label values d8_eng d8_eng_
label values d9_eng d9_eng_
label values d10_eng d10_eng_
label values d11_eng d11_eng_
label values d12_eng d12_eng_
label values d13_eng d13_eng_
label values d14_eng d14_eng_
label values d15_eng d15_eng_
label values d16_eng d16_eng_
label values d17_eng d17_eng_
label values d18_eng d18_eng_
label values d19_eng d19_eng_
label values d20_eng d20_eng_
label values d21_eng d21_eng_
label values d22_eng d22_eng_
label values d23_eng d23_eng_
label values hiv_know1 hiv_know1_
label values hiv_know2 hiv_know2_
label values hiv_know3 hiv_know3_
label values hiv_know4 hiv_know4_
label values hiv_know5 hiv_know5_
label values hiv_know6 hiv_know6_
label values hiv_know7 hiv_know7_
label values hiv_know8 hiv_know8_
label values hiv_know9 hiv_know9_
label values hiv_know10 hiv_know10_
label values hiv_know11 hiv_know11_
label values hiv_know12 hiv_know12_
label values hiv_know13 hiv_know13_
label values hiv_know14 hiv_know14_
label values hiv_know15 hiv_know15_
label values hiv_know16 hiv_know16_
label values hiv_know17 hiv_know17_
label values hiv_know18 hiv_know18_
label values s5_q1_p s5_q1_p_
label values s5_q2_p s5_q2_p_
label values s5_q3_p s5_q3_p_
label values s5_q4_p s5_q4_p_
label values s5_q5_p s5_q5_p_
label values s5_q6_p s5_q6_p_
label values s5_q7_p s5_q7_p_
label values s5_q8_p s5_q8_p_
label values s5_q9_p s5_q9_p_
label values s5_q10_p s5_q10_p_
label values s5_q11_p s5_q11_p_
label values s5_q12_p s5_q12_p_
label values s5_q13_p s5_q13_p_
label values s5_q14_p s5_q14_p_
label values tb_know1 tb_know1_
label values tb_know2 tb_know2_
label values tb_know3 tb_know3_
label values tb_know4 tb_know4_
label values tb_know5 tb_know5_
label values tb_know6 tb_know6_
label values tb_know7 tb_know7_
label values tb_know8 tb_know8_
label values tb_know9 tb_know9_
label values tb_know10 tb_know10_
label values tb_know11 tb_know11_
label values s6_q1 s6_q1_
label values s6_q2 s6_q2_
label values s6_q3 s6_q3_
label values s6_q4 s6_q4_
label values s6_q5 s6_q5_
label values s6_q6 s6_q6_
label values s6_q7 s6_q7_
label values s6_q8 s6_q8_
label values s6_q9 s6_q9_
label values s6_q10 s6_q10_
label values a1_eng a1_eng_
label values a2_eng a2_eng_
label values a3_eng a3_eng_
label values a4_eng a4_eng_
label values a5_eng a5_eng_
label values a6_eng a6_eng_
label values a7_eng a7_eng_
label values a8_eng a8_eng_
label values a9_eng a9_eng_
label values a10_eng a10_eng_
label values a11_eng a11_eng_
label values a12_eng a12_eng_
label values a17_eng a17_eng_
label values a29_eng a29_eng_
label values a30_eng a30_eng_
label values a31_eng a31_eng_
label values a32_eng a32_eng_
label values a33_eng a33_eng_
label values a34_eng a34_eng_
label values a35_eng a35_eng_
label values a36_eng a36_eng_
label values a37_eng a37_eng_
label values a38_eng a38_eng_
label values a39_eng a39_eng_
label values a40_eng a40_eng_
label values a41_eng a41_eng_
label values a42_eng a42_eng_
label values a43_eng a43_eng_
label values a44_eng a44_eng_
label values b1_eng b1_eng_
label values b2_eng b2_eng_
label values b3_eng b3_eng_
label values b4_eng b4_eng_
label values b5_eng b5_eng_
label values b6_eng b6_eng_
label values b7_eng b7_eng_
label values b8_eng b8_eng_
label values b9_eng b9_eng_
label values b10_eng b10_eng_
label values b11_eng b11_eng_
label values b12_eng b12_eng_
label values b13_eng b13_eng_
label values b14_eng b14_eng_
label values b15_eng b15_eng_
label values b16_eng b16_eng_
label values b17_eng b17_eng_
label values b18_eng b18_eng_
label values b19_eng b19_eng_
label values b20_eng b20_eng_
label values b21_eng b21_eng_
label values b22_eng b22_eng_
label values b23_eng b23_eng_
label values b24_eng b24_eng_
label values b25_eng b25_eng_
label values b26_eng b26_eng_
label values b27_eng b27_eng_
label values b28_eng b28_eng_
label values b29_eng b29_eng_
label values b30_eng b30_eng_
label values b31_eng b31_eng_
label values b32_eng b32_eng_
label values maks1 maks1_
label values maks2 maks2_
label values maks3 maks3_
label values maks4 maks4_
label values maks5 maks5_
label values maks6 maks6_
label values maks7 maks7_
label values maks8 maks8_
label values maks9 maks9_
label values maks10 maks10_
label values maks11 maks11_
label values maks12 maks12_
label values bog_1 bog_1_
label values bog_2 bog_2_
label values bog_3 bog_3_
label values bog_4 bog_4_
label values bog_5 bog_5_
label values bog_6 bog_6_
label values pss1_eng pss1_eng_
label values pss2_eng pss2_eng_
label values pss3_eng pss3_eng_
label values pss4_eng pss4_eng_
label values pss5_eng pss5_eng_
label values pss6_eng pss6_eng_
label values pss7_eng pss7_eng_
label values pss8_eng pss8_eng_
label values pss9_eng pss9_eng_
label values pss10_eng pss10_eng_
label values stig1_eng stig1_eng_
label values stig2_eng stig2_eng_
label values stig3_eng stig3_eng_
label values stig4_eng stig4_eng_
label values end_instruct end_instruct_
label values questionnaires_complete questionnaires_complete_
label values is_the_participant_able_to is_the_participant_able_to_
label values prs_complete prs_complete_
label values study_note_avail_1 study_note_avail_1_
label values specify_the_seriousness_of_1 specify_the_seriousness_of_1_
label values the_study_note_is_addresse_1 the_study_note_is_addresse_1_
label values study_notes_complete_1 study_notes_complete_1_
label values study_note_avail_2 study_note_avail_2_
label values specify_the_seriousness_of_2 specify_the_seriousness_of_2_
label values the_study_note_is_addresse_2 the_study_note_is_addresse_2_
label values study_notes_complete_2 study_notes_complete_2_
label values study_note_avail_3 study_note_avail_3_
label values specify_the_seriousness_of_3 specify_the_seriousness_of_3_
label values the_study_note_is_addresse_3 the_study_note_is_addresse_3_
label values study_notes_complete_3 study_notes_complete_3_
label values screening_and_consent_2_in screening_and_consent_2_in_
label values demo_qc demo_qc_
label values questionnaires_proof_of_sn questionnaires_proof_of_sn_
label values proof_of_snack_7_study_not proof_of_snack_7_study_not_
label values study_note study_note_
label values iqc_complete iqc_complete_
