label define ra_instruct_ 1 "Continue" 
label define attempt_ 1 "1st attempt" 2 "2nd attempt" 3 "3rd attempt" 
label define ra_instruct_1stattempt_ 1 "I confirm that I recorded the house number on the Google Maps App" 
label define ra_instruct_2nd_3rdattempt_ 1 "I confirm that the household number on Google Maps is accurate" 
label define hhl_complete_ 0 "Incomplete" 1 "Unverified" 2 "Complete" 
label define area_1_ 1 "Duncan Village" 2 "Scenery Park" 3 "Nompumelelo" 4 "Ducats" 5 "Mdantsane" 6 "Ndevana" 7 "Ginsberg" 8 "Buffalo Flats" 9 "Zwelitsha" 
label define study_community_1_ 1 "1" 2 "2" 3 "3" 4 "4" 5 "5" 6 "6" 7 "7" 8 "8" 9 "9" 10 "10" 11 "11" 12 "12" 13 "13" 14 "14" 15 "15" 16 "16" 17 "17" 18 "18" 19 "19" 20 "20" 21 "21" 22 "22" 23 "23" 24 "24" 25 "25" 26 "26" 27 "27" 28 "28" 29 "29" 30 "30" 31 "31" 32 "32" 33 "33" 34 "34" 35 "35" 36 "36" 37 "37" 38 "38" 39 "39" 40 "40" 41 "41" 42 "42" 43 "43" 44 "44" 45 "45" 46 "46" 47 "47" 48 "48" 49 "49" 50 "50" 
label define square_number_1_ 1 "1" 2 "2" 3 "3" 4 "4" 5 "5" 6 "6" 7 "7" 8 "8" 9 "9" 10 "10" 11 "11" 12 "12" 13 "13" 14 "14" 15 "15" 
label define sub_square_letter_1_ 1 "A" 2 "B" 3 "C" 4 "D" 5 "Not applicable" 
label define confirm_infrontofgate_door_1_ 1 "I confirm that I am at the gate / door" 
label define hhmember_present_1_ 1 "Yes" 2 "No" 
label define hh_not_present_confirm_1_ 1 "I confirm" 
label define intro_script1_1_ 1 "Read the script out loud to the person" 
label define hoh_at_home_1_ 1 "Yes - the person who opened the door is calling the HoH" 2 "Yes - the person who opened the door is the HoH" 3 "No" 
label define intro_script_2_1_ 1 "Read the script out loud to the HoH" 
label define interest_status_1_ 1 "Yes" 0 "No" 
label define area_2_ 1 "Duncan Village" 2 "Scenery Park" 3 "Nompumelelo" 4 "Ducats" 5 "Mdantsane" 6 "Ndevana" 7 "Ginsberg" 8 "Buffalo Flats" 9 "Zwelitsha" 
label define study_community_2_ 1 "1" 2 "2" 3 "3" 4 "4" 5 "5" 6 "6" 7 "7" 8 "8" 9 "9" 10 "10" 11 "11" 12 "12" 13 "13" 14 "14" 15 "15" 16 "16" 17 "17" 18 "18" 19 "19" 20 "20" 21 "21" 22 "22" 23 "23" 24 "24" 25 "25" 26 "26" 27 "27" 28 "28" 29 "29" 30 "30" 31 "31" 32 "32" 33 "33" 34 "34" 35 "35" 36 "36" 37 "37" 38 "38" 39 "39" 40 "40" 41 "41" 42 "42" 43 "43" 44 "44" 45 "45" 46 "46" 47 "47" 48 "48" 49 "49" 50 "50" 
label define square_number_2_ 1 "1" 2 "2" 3 "3" 4 "4" 5 "5" 6 "6" 7 "7" 8 "8" 9 "9" 10 "10" 11 "11" 12 "12" 13 "13" 14 "14" 15 "15" 
label define sub_square_letter_2_ 1 "A" 2 "B" 3 "C" 4 "D" 5 "Not applicable" 
label define confirm_infrontofgate_door_2_ 1 "I confirm that I am at the gate / door" 
label define hhmember_present_2_ 1 "Yes" 2 "No" 
label define hh_not_present_confirm_2_ 1 "I confirm" 
label define intro_script1_2_ 1 "Read the script out loud to the person" 
label define hoh_at_home_2_ 1 "Yes - the person who opened the door is calling the HoH" 2 "Yes - the person who opened the door is the HoH" 3 "No" 
label define intro_script_2_2_ 1 "Read the script out loud to the HoH" 
label define interest_status_2_ 1 "Yes" 0 "No" 
label define area_3_ 1 "Duncan Village" 2 "Scenery Park" 3 "Nompumelelo" 4 "Ducats" 5 "Mdantsane" 6 "Ndevana" 7 "Ginsberg" 8 "Buffalo Flats" 9 "Zwelitsha" 
label define study_community_3_ 1 "1" 2 "2" 3 "3" 4 "4" 5 "5" 6 "6" 7 "7" 8 "8" 9 "9" 10 "10" 11 "11" 12 "12" 13 "13" 14 "14" 15 "15" 16 "16" 17 "17" 18 "18" 19 "19" 20 "20" 21 "21" 22 "22" 23 "23" 24 "24" 25 "25" 26 "26" 27 "27" 28 "28" 29 "29" 30 "30" 31 "31" 32 "32" 33 "33" 34 "34" 35 "35" 36 "36" 37 "37" 38 "38" 39 "39" 40 "40" 41 "41" 42 "42" 43 "43" 44 "44" 45 "45" 46 "46" 47 "47" 48 "48" 49 "49" 50 "50" 
label define square_number_3_ 1 "1" 2 "2" 3 "3" 4 "4" 5 "5" 6 "6" 7 "7" 8 "8" 9 "9" 10 "10" 11 "11" 12 "12" 13 "13" 14 "14" 15 "15" 
label define sub_square_letter_3_ 1 "A" 2 "B" 3 "C" 4 "D" 5 "Not applicable" 
label define confirm_infrontofgate_door_3_ 1 "I confirm that I am at the gate / door" 
label define hhmember_present_3_ 1 "Yes" 2 "No" 
label define hh_not_present_confirm_3_ 1 "I confirm" 
label define intro_script1_3_ 1 "Read the script out loud to the person" 
label define hoh_at_home_3_ 1 "Yes - the person who opened the door is calling the HoH" 2 "Yes - the person who opened the door is the HoH" 3 "No" 
label define intro_script_2_3_ 1 "Read the script out loud to the HoH" 
label define interest_status_3_ 1 "Yes" 0 "No" 
label define screening_for_eligibility_ 1 "Proceed" 
label define participant_gender_ 1 "Female" 2 "Male" 
label define lang_fluent_ 1 "One or both" 2 "Neither" 
label define community_ 1 "Yes" 0 "No" 
label define ra_the_participant_is_elig_ 1 "Proceed" 
label define ra_the_person_is_not_eligi_ 1 "END" 
label define note_to_ra_you_will_now_st_ 1 "Proceed" 
label define preferred_language_to_be_u_ 1 "English" 2 "Xhosa" 
label define did_the_person_consent_to_ 1 "Yes" 0 "No" 
label define participant_can_sign_ 1 "Yes" 0 "No" 
label define refconfirm_ 1 "END" 
label define consented_the_person_has_a_ 1 "Generate" 
label define pin_display_ 1 "Proceed" 
label define consent_qc_1_ 1 "Checked, completed" 
label define consent_qc_2_ 1 "Checked, completed" 
label define consent_qc_3_ 1 "Checked, completed" 
label define contact_no_2_ 1 "Myself (Participant)" 2 "Sibling" 3 "Partner/Spouse" 4 "Child" 5 "Other" 
label define sc_complete_ 0 "Incomplete" 1 "Unverified" 2 "Complete" 
label define language_prefer_ 1 "English" 2 "isiXhosa" 
label define other_studies_ 0 "No" 1 "Yes" 
label define other_studies_time_e_ 1 "In the last 6 months" 2 "More than 6 months ago" 
label define s1_q1_ 1 "White" 2 "Black" 3 "Indian" 4 "Colored" 5 "Other, Specify" 
label define place_of_birth_rsa_e_ 1 "Yes" 0 "No" 
label define place_of_birth_other_ 1 "Namibia" 2 "Zimbabwe" 3 "Mozambique" 4 "Botswana" 5 "Other" 
label define s1_q5_ 1 "Married / civil union" 2 "Steady partner" 3 "Single" 4 "Divorced" 5 "Widowed" 
label define living_arrangement_e_ 1 "Yes" 0 "No" 
label define s1_q6_ 1 "Less than Matric" 2 "Matric" 3 "Tertiary" 
label define s1_q7_ 1 "Employed full-time" 2 "Employed part-time" 3 "Self-Employed" 4 "Unemployed" 
label define s1_q14_ 1 "Under R1000" 2 "R1000 - R2500" 3 "R2501 - R5000" 4 "R5001 - R7500" 5 "R7501 - R10 000" 6 "R10 001 - R20 000" 7 "More than R 20 000" 
label define s2_q2_ 1 "Never" 2 "Yes, less than 2 years ago" 3 "Yes, more than 2 years ago" 
label define hoh_tb_hist_clinic_ 1 "ec Chris Hani Clinic" 2 "ec Duncan Village CHC" 3 "ec Fezeka NU 3 Clinic" 4 "ec Ginsberg Clinic" 5 "ec Gompo A Ndende Clinic" 6 "ec Gompo B Jwayi Clinic" 7 "ec Gompo C Jabavu Clinic" 8 "ec Grey Gateway Clinic" 9 "ec John Dube Clinic" 10 "ec Luyolo NU 9 Clinic" 11 "ec Ndevana Clinic" 12 "ec NU 12 Clinic" 13 "ec NU 13 Clinic" 14 "ec Pefferville Clinic" 15 "ec Philani NU 1 Clinic" 16 "ec Aspiranza Clinic" 17 "ec Alphendale Clinic" 18 "ec Zwelitsha Zone 5 Clinic" 19 "ec Empilweni Gompo CHC" 20 "ec Pakamisa Clinic" 21 "Other" 
label define hhm_tb_e_ 1 "Never" 2 "Yes, less than 2 years ago" 3 "Yes, more than 2 years ago" 
label define hhm_tb_hist_clinic_ 1 "ec Chris Hani Clinic" 2 "ec Duncan Village CHC" 3 "ec Fezeka NU 3 Clinic" 4 "ec Ginsberg Clinic" 5 "ec Gompo A Ndende Clinic" 6 "ec Gompo B Jwayi Clinic" 7 "ec Gompo C Jabavu Clinic" 8 "ec Grey Gateway Clinic" 9 "ec John Dube Clinic" 10 "ec Luyolo NU 9 Clinic" 11 "ec Ndevana Clinic" 12 "ec NU 12 Clinic" 13 "ec NU 13 Clinic" 14 "ec Pefferville Clinic" 15 "ec Philani NU 1 Clinic" 16 "ec Aspiranza Clinic" 17 "ec Alphendale Clinic" 18 "ec Zwelitsha Zone 5 Clinic" 19 "ec Empilweni Gompo CHC" 20 "ec Pakamisa Clinic" 21 "Other" 
label define s2_q3_ 1 "Yes" 0 "No" 2 "I dont know" 
label define s2_q5_ 1 "Never" 2 "Yes, less than 6 months ago" 3 "Yes, in the last year, but more than 6 months ago" 4 "Yes, more than a year ago" 
label define hh_member_hiv_ 1 "Yes" 2 "No" 
label define s2_q9_ 1 "Yes" 0 "No" 2 "I dont know" 
label define s5_q1___1_ 0 "Unchecked" 1 "Checked" 
label define s5_q1___2_ 0 "Unchecked" 2 "Checked" 
label define s5_q1___3_ 0 "Unchecked" 3 "Checked" 
label define s5_q1___4_ 0 "Unchecked" 4 "Checked" 
label define s5_q1___5_ 0 "Unchecked" 5 "Checked" 
label define s5_q1___6_ 0 "Unchecked" 6 "Checked" 
label define s5_q1___7_ 0 "Unchecked" 7 "Checked" 
label define s5_q1___8_ 0 "Unchecked" 8 "Checked" 
label define s5_q1___9_ 0 "Unchecked" 9 "Checked" 
label define s5_q2___1_ 0 "Unchecked" 1 "Checked" 
label define s5_q2___2_ 0 "Unchecked" 2 "Checked" 
label define s5_q2___3_ 0 "Unchecked" 3 "Checked" 
label define s5_q2___4_ 0 "Unchecked" 4 "Checked" 
label define s5_q2___5_ 0 "Unchecked" 5 "Checked" 
label define s5_q2___6_ 0 "Unchecked" 6 "Checked" 
label define s5_q2___7_ 0 "Unchecked" 7 "Checked" 
label define s5_q3___1_ 0 "Unchecked" 1 "Checked" 
label define s5_q3___2_ 0 "Unchecked" 2 "Checked" 
label define s5_q3___3_ 0 "Unchecked" 3 "Checked" 
label define s5_q3___4_ 0 "Unchecked" 4 "Checked" 
label define s5_q3___5_ 0 "Unchecked" 5 "Checked" 
label define s5_q3___6_ 0 "Unchecked" 6 "Checked" 
label define s5_q3___7_ 0 "Unchecked" 7 "Checked" 
label define s5_q3___8_ 0 "Unchecked" 8 "Checked" 
label define s5_q3___9_ 0 "Unchecked" 9 "Checked" 
label define s5_q3___10_ 0 "Unchecked" 10 "Checked" 
label define s5_q3___11_ 0 "Unchecked" 11 "Checked" 
label define s5_q4_ 1 "Yes" 0 "No" 3 "I dont know" 
label define s5_q5_ 1 "Yes" 0 "No" 3 "I dont know" 
label define mental_health_history_e___1_ 0 "Unchecked" 1 "Checked" 
label define mental_health_history_e___2_ 0 "Unchecked" 1 "Checked" 
label define mental_health_history_e___3_ 0 "Unchecked" 1 "Checked" 
label define mental_health_history_e___4_ 0 "Unchecked" 1 "Checked" 
label define mental_health_history_e___5_ 0 "Unchecked" 1 "Checked" 
label define mental_health_history_e___6_ 0 "Unchecked" 1 "Checked" 
label define mental_health_history_e___7_ 0 "Unchecked" 1 "Checked" 
label define mental_health_history_e___8_ 0 "Unchecked" 1 "Checked" 
label define mental_health_history_e___9_ 0 "Unchecked" 1 "Checked" 
label define mental_health_history_e___10_ 0 "Unchecked" 1 "Checked" 
label define mental_health_history_e___11_ 0 "Unchecked" 1 "Checked" 
label define mental_health_history_e___ni_ 0 "Unchecked" 1 "Checked" 
label define mental_health_history_e___nav_ 0 "Unchecked" 1 "Checked" 
label define mental_health_history2_e_ 1 "Yes" 0 "No" 
label define fam_mental_health1_e_ 1 "Yes" 0 "No" 
label define fam_mental_health2_e_ 1 "Yes" 0 "No" 
label define gender_hhm_1_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define gender_hhm_2_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define gender_hhm_3_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define gender_hhm_4_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define gender_hhm_5_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define gender_hhm_6_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define gender_hhm_7_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define gender_hhm_8_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define gender_hhm_9_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define gender_hhm_10_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define gender_hhm_11_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define gender_hhm_12_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define gender_hhm_13_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define gender_hhm_14_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define gender_hhm_15_ 1 "Female/ Ibhinqa" 2 "Male/ Indoda" 
label define age6to13_confirm_ 1 "There are children between the age of 6 and 13 living in this HH" 2 "There are NO children between the age of 6 and 13 living in this HH" 
label define highest_education_ 1 "No education/did not attend primary school" 2 "Some primary" 3 "Completed primary" 4 "Some secondary" 5 "Completed secondary" 6 "Tertiary or post-secondary certification" 
label define highest_primary_ 1 "Grade 1" 2 "Grade 2" 3 "Grade 3" 4 "Grade 4" 5 "Grade 5" 6 "Grade 6" 7 "Grade 7" 
label define highest_grade_ofall_ 1 "No education/did not attend primary school" 2 "Some primary" 3 "Completed primary" 4 "Some secondary" 5 "Completed secondary" 6 "Tertiary or post-secondary certification" 
label define highest_primary_ofall_ 1 "Grade 1" 2 "Grade 2" 3 "Grade 3" 4 "Grade 4" 5 "Grade 5" 6 "Grade 6" 7 "Grade 7" 
label define attend_school_ 1 "Yes" 0 "No" 
label define highest_grade_notattending_ 1 "None" 2 "Grade 1" 3 "Grade 2" 4 "Grade 3" 5 "Grade 4" 6 "Grade 5" 7 "Grade 6" 8 "Grade 7" 
label define child_mortality_ 1 "Yes" 0 "No" 
label define drinking_water_e_ 1 "Piped into dwelling/house" 2 "Piped to yard/plot" 3 "Piped to neighbor" 4 "Public/communal tap" 5 "Borehole" 6 "Protected well" 7 "Unprotected well" 8 "Protected spring" 9 "Unprotected spring" 10 "Rainwater" 11 "Water-carrier/Tanker truck" 12 "Cart with small tank/Water vendor" 13 "Surface water (river/lake/dam/pond/stream/canal/irrigation channel)" 14 "Bottled water" 15 "Other" 
label define water_located_e_ 1 "In own dwelling" 2 "In own yard/plot" 3 "Elsewhere/outside yard" 
label define toilet_e_ 1 "Flush to piped sewer system" 2 "Flush to septic tank" 3 "Flush to pit latrine" 4 "Flush to somewhere else" 5 "Flush, dont know where" 6 "Ventilated improved pit latrine" 7 "Pit latrine with ventilation pipe but no gauze/mesh/netting" 8 "Pit latrine without ventilation pipe" 9 "Composting toilet/ecological sanitation system" 10 "Chemical toilet" 11 "Bucket toilet" 12 "No facility/bush/field" 
label define fuel_e_ 1 "Electricity from mains" 2 "Electricity from generator" 3 "Electricity from other source" 4 "Solar energy" 5 "Gas" 6 "Paraffin" 7 "Coal" 8 "Wood" 9 "Straw/Shrubs/Grass" 10 "Agricultural crop" 11 "Animal dung" 12 "No food cooked in household" 13 "Other" 
label define cooking_place_e_ 1 "In the house" 2 "In a separate building" 3 "Outdoors" 4 "Other" 
label define seperate_cook_space_e_ 1 "Yes" 0 "No" 
label define seperate_cook_space_e_2_ 1 "Ewe" 0 "Hayi" 
label define mains_elec_e_ 1 "Yes" 0 "No" 
label define asset1_ 1 "Yes" 0 "No" 
label define asset2_ 1 "Yes" 0 "No" 
label define asset3_ 1 "Yes" 0 "No" 
label define asset4_ 1 "Yes" 0 "No" 
label define asset5_ 1 "Yes" 0 "No" 
label define asset6_ 1 "Yes" 0 "No" 
label define asset7_ 1 "Yes" 0 "No" 
label define asset8_ 1 "Yes" 0 "No" 
label define asset9_ 1 "Yes" 0 "No" 
label define own1_ 1 "Yes" 0 "No" 
label define own2_ 1 "Yes" 0 "No" 
label define own3_ 1 "Yes" 0 "No" 
label define own4_ 1 "Yes" 0 "No" 
label define own5_ 1 "Yes" 0 "No" 
label define own6_ 1 "Yes" 0 "No" 
label define own7_ 1 "Yes" 0 "No" 
label define floor_ 1 "Earth/sand" 2 "Dung" 3 "Wood planks" 4 "Laminated or Polished Wood" 5 "Vinyl/asphalt strips" 6 "Ceramic tiles" 7 "Cement" 8 "Carpet" 9 "Other" 
label define roof_ 1 "No roof" 2 "Thatching/grass" 3 "Mud/sod" 4 "Plastic" 5 "Wattle and daub" 6 "Mud with cement mix" 7 "Bricks" 8 "Wood planks" 9 "Cardboard" 10 "Corrugated metal" 11 "Wood" 12 "Asbestos" 13 "Tiles" 14 "Cements" 15 "Other" 
label define fam_decision_1_ 1 "Respondent/Participant" 2 "Spouse/partner" 3 "Respondent/Participant and Spouse/partner jointly" 4 "Someone else" 
label define fam_decision_2_ 1 "Respondent/Participant" 2 "Spouse/partner" 3 "Respondent/Participant and Spouse/partner jointly" 4 "Someone else" 
label define fam_decision_3_ 1 "Respondent/Participant" 2 "Spouse/partner" 3 "Respondent/Participant and Spouse/partner jointly" 4 "Someone else" 
label define navigate_tablet_e_ 1 "Yes" 0 "No" 
label define ra_note_e_ 1 "Proceed" 
label define literate_check_e_ 1 "Yes" 0 "No" 
label define f1_ 1 "Not at all" 2 "Somewhat" 3 "A lot" 
label define f2_ 1 "Not at all" 2 "Somewhat" 3 "A lot" 
label define f3_ 1 "Not at all" 2 "Somewhat" 3 "A lot" 
label define fun1___1_ 0 "Unchecked" 1 "Checked" 
label define fun1___2_ 0 "Unchecked" 1 "Checked" 
label define fun1___3_ 0 "Unchecked" 1 "Checked" 
label define fun1___4_ 0 "Unchecked" 1 "Checked" 
label define fun1___5_ 0 "Unchecked" 1 "Checked" 
label define fun1___6_ 0 "Unchecked" 1 "Checked" 
label define fun2_ 1 "Botswana" 2 "Jamaica" 3 "France" 4 "United States of America" 5 "Other" 
label define instruct_part_ 1 "Research Assistant please click here" 
label define hhd_complete_ 0 "Incomplete" 1 "Unverified" 2 "Complete" 
label define ques_language_ 1 "English" 2 "IsiXhosa" 
label define hoh_last_clinic_any_e_ 1 "ec Chris Hani Clinic" 2 "ec Duncan Village CHC" 3 "ec Fezeka NU 3 Clinic" 4 "ec Ginsberg Clinic" 5 "ec Gompo A Ndende Clinic" 6 "ec Gompo B Jwayi Clinic" 7 "ec Gompo C Jabavu Clinic" 8 "ec Grey Gateway Clinic" 9 "ec John Dube Clinic" 10 "ec Luyolo NU 9 Clinic" 11 "ec Ndevana Clinic" 12 "ec NU 12 Clinic" 13 "ec NU 13 Clinic" 14 "ec Pefferville Clinic" 15 "ec Philani NU 1 Clinic" 16 "ec Aspiranza Clinic" 17 "ec Alphendale Clinic" 18 "ec Zwelitsha Zone 5 Clinic" 19 "ec Empilweni Gompo CHC" 20 "ec Pakamisa Clinic" 21 "Other" 
label define symptom_preffered_clinic_ 1 "ec Chris Hani Clinic" 2 "ec Duncan Village CHC" 3 "ec Fezeka NU 3 Clinic" 4 "ec Ginsberg Clinic" 5 "ec Gompo A Ndende Clinic" 6 "ec Gompo B Jwayi Clinic" 7 "ec Gompo C Jabavu Clinic" 8 "ec Grey Gateway Clinic" 9 "ec John Dube Clinic" 10 "ec Luyolo NU 9 Clinic" 11 "ec Ndevana Clinic" 12 "ec NU 12 Clinic" 13 "ec NU 13 Clinic" 14 "ec Pefferville Clinic" 15 "ec Philani NU 1 Clinic" 16 "ec Aspiranza Clinic" 17 "ec Alphendale Clinic" 18 "ec Zwelitsha Zone 5 Clinic" 19 "ec Empilweni Gompo CHC" 20 "ec Pakamisa Clinic" 21 "Other" 
label define tb_diagnosed_clinic_prefer_ 1 "ec Chris Hani Clinic" 2 "ec Duncan Village CHC" 3 "ec Fezeka NU 3 Clinic" 4 "ec Ginsberg Clinic" 5 "ec Gompo A Ndende Clinic" 6 "ec Gompo B Jwayi Clinic" 7 "ec Gompo C Jabavu Clinic" 8 "ec Grey Gateway Clinic" 9 "ec John Dube Clinic" 10 "ec Luyolo NU 9 Clinic" 11 "ec Ndevana Clinic" 12 "ec NU 12 Clinic" 13 "ec NU 13 Clinic" 14 "ec Pefferville Clinic" 15 "ec Philani NU 1 Clinic" 16 "ec Aspiranza Clinic" 17 "ec Alphendale Clinic" 18 "ec Zwelitsha Zone 5 Clinic" 19 "ec Empilweni Gompo CHC" 20 "ec Pakamisa Clinic" 21 "Other" 
label define hiv_clinic_prefer_test_ 1 "ec Chris Hani Clinic" 2 "ec Duncan Village CHC" 3 "ec Fezeka NU 3 Clinic" 4 "ec Ginsberg Clinic" 5 "ec Gompo A Ndende Clinic" 6 "ec Gompo B Jwayi Clinic" 7 "ec Gompo C Jabavu Clinic" 8 "ec Grey Gateway Clinic" 9 "ec John Dube Clinic" 10 "ec Luyolo NU 9 Clinic" 11 "ec Ndevana Clinic" 12 "ec NU 12 Clinic" 13 "ec NU 13 Clinic" 14 "ec Pefferville Clinic" 15 "ec Philani NU 1 Clinic" 16 "ec Aspiranza Clinic" 17 "ec Alphendale Clinic" 18 "ec Zwelitsha Zone 5 Clinic" 19 "ec Empilweni Gompo CHC" 20 "ec Pakamisa Clinic" 21 "Other" 
label define hiv_clinic_prefer_treat_ 1 "ec Chris Hani Clinic" 2 "ec Duncan Village CHC" 3 "ec Fezeka NU 3 Clinic" 4 "ec Ginsberg Clinic" 5 "ec Gompo A Ndende Clinic" 6 "ec Gompo B Jwayi Clinic" 7 "ec Gompo C Jabavu Clinic" 8 "ec Grey Gateway Clinic" 9 "ec John Dube Clinic" 10 "ec Luyolo NU 9 Clinic" 11 "ec Ndevana Clinic" 12 "ec NU 12 Clinic" 13 "ec NU 13 Clinic" 14 "ec Pefferville Clinic" 15 "ec Philani NU 1 Clinic" 16 "ec Aspiranza Clinic" 17 "ec Alphendale Clinic" 18 "ec Zwelitsha Zone 5 Clinic" 19 "ec Empilweni Gompo CHC" 20 "ec Pakamisa Clinic" 21 "Other" 
label define non_tb_care_util_ 1 "Within the last 6 months" 2 "6 to 12 months" 3 "1-2 years" 4 "More than 2 years ago" 
label define type_health_util___1_ 0 "Unchecked" 1 "Checked" 
label define type_health_util___2_ 0 "Unchecked" 1 "Checked" 
label define type_health_util___3_ 0 "Unchecked" 1 "Checked" 
label define type_health_util___4_ 0 "Unchecked" 1 "Checked" 
label define prison_ 1 "Yes" 0 "No" 
label define prison_time_ 1 "Less than a year" 2 "More than a year" 
label define prison_release_ 1 "Within the past five years" 2 "More than 5 years ago" 
label define mines_ 1 "Yes" 0 "No" 
label define mines_time_ 1 "Less than a year" 2 "More than a year" 
label define mines_long_ago_ 1 "Within the past five years" 2 "More than 5 years ago" 
label define ss1_ 1 "Very Strongly Disagree" 2 "Strongly Disagree" 3 "Mildly Disagree" 4 "Neutral" 5 "Mildly Agree" 6 "Strongly Agree" 7 "Very Strongly Agree" 
label define ss2_ 1 "Very Strongly Disagree" 2 "Strongly Disagree" 3 "Mildly Disagree" 4 "Neutral" 5 "Mildly Agree" 6 "Strongly Agree" 7 "Very Strongly Agree" 
label define ss3_ 1 "Very Strongly Disagree" 2 "Strongly Disagree" 3 "Mildly Disagree" 4 "Neutral" 5 "Mildly Agree" 6 "Strongly Agree" 7 "Very Strongly Agree" 
label define ss4_ 1 "Very Strongly Disagree" 2 "Strongly Disagree" 3 "Mildly Disagree" 4 "Neutral" 5 "Mildly Agree" 6 "Strongly Agree" 7 "Very Strongly Agree" 
label define ss5_ 1 "Very Strongly Disagree" 2 "Strongly Disagree" 3 "Mildly Disagree" 4 "Neutral" 5 "Mildly Agree" 6 "Strongly Agree" 7 "Very Strongly Agree" 
label define ss6_ 1 "Very Strongly Disagree" 2 "Strongly Disagree" 3 "Mildly Disagree" 4 "Neutral" 5 "Mildly Agree" 6 "Strongly Agree" 7 "Very Strongly Agree" 
label define ss7_ 1 "Very Strongly Disagree" 2 "Strongly Disagree" 3 "Mildly Disagree" 4 "Neutral" 5 "Mildly Agree" 6 "Strongly Agree" 7 "Very Strongly Agree" 
label define ss8_ 1 "Very Strongly Disagree" 2 "Strongly Disagree" 3 "Mildly Disagree" 4 "Neutral" 5 "Mildly Agree" 6 "Strongly Agree" 7 "Very Strongly Agree" 
label define ss9_ 1 "Very Strongly Disagree" 2 "Strongly Disagree" 3 "Mildly Disagree" 4 "Neutral" 5 "Mildly Agree" 6 "Strongly Agree" 7 "Very Strongly Agree" 
label define ss10_ 1 "Very Strongly Disagree" 2 "Strongly Disagree" 3 "Mildly Disagree" 4 "Neutral" 5 "Mildly Agree" 6 "Strongly Agree" 7 "Very Strongly Agree" 
label define ss11_ 1 "Very Strongly Disagree" 2 "Strongly Disagree" 3 "Mildly Disagree" 4 "Neutral" 5 "Mildly Agree" 6 "Strongly Agree" 7 "Very Strongly Agree" 
label define ss12_ 1 "Very Strongly Disagree" 2 "Strongly Disagree" 3 "Mildly Disagree" 4 "Neutral" 5 "Mildly Agree" 6 "Strongly Agree" 7 "Very Strongly Agree" 
label define e1_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Agree" 4 "Strongly Agree" 
label define e2_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Agree" 4 "Strongly Agree" 
label define e3_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Agree" 4 "Strongly Agree" 
label define e4_eng_ 1 "People can be trusted" 2 "You cant be too careful" 3 "Depends" 
label define e5_eng_ 4 "Trust them alot" 3 "Some" 2 "Only a little" 1 "Not at all" 0 "Doesnt apply" 
label define e6_eng_ 4 "Trust them alot" 3 "Some" 2 "Only a little" 1 "Not at all" 0 "Doesnt apply" 
label define e7_eng_ 4 "Trust them alot" 3 "Some" 2 "Only a little" 1 "Not at all" 0 "Doesnt apply" 
label define e8_eng_ 4 "Trust them alot" 3 "Some" 2 "Only a little" 1 "Not at all" 0 "Doesnt apply" 
label define e9_eng_ 4 "Trust them alot" 3 "Some" 2 "Only a little" 1 "Not at all" 0 "Doesnt apply" 
label define e10_eng_ 4 "Trust them alot" 3 "Some" 2 "Only a little" 1 "Not at all" 0 "Doesnt apply" 
label define e11_eng_ 4 "Trust them alot" 3 "Some" 2 "Only a little" 1 "Not at all" 0 "Doesnt apply" 
label define e12_eng_ 4 "Trust them alot" 3 "Some" 2 "Only a little" 1 "Not at all" 0 "Doesnt apply" 
label define e13_eng_ 4 "Trust them alot" 3 "Some" 2 "Only a little" 1 "Not at all" 0 "Doesnt apply" 
label define e14_eng_ 4 "Trust them alot" 3 "Some" 2 "Only a little" 1 "Not at all" 0 "Doesnt apply" 
label define e15_eng_ 4 "Trust them alot" 3 "Some" 2 "Only a little" 1 "Not at all" 0 "Doesnt apply" 
label define e16_eng_ 4 "Trust them alot" 3 "Some" 2 "Only a little" 1 "Not at all" 0 "Doesnt apply" 
label define e17_eng_ 4 "Trust them alot" 3 "Some" 2 "Only a little" 1 "Not at all" 0 "Doesnt apply" 
label define e18_eng_ 4 "Trust them alot" 3 "Some" 2 "Only a little" 1 "Not at all" 0 "Doesnt apply" 
label define e21_eng_ 3 "Very Likely" 2 "Somewhat Likely" 1 "Not Likely at all" 
label define e22_eng_ 3 "Very Likely" 2 "Somewhat Likely" 1 "Not Likely at all" 
label define e23_eng_ 3 "Very Likely" 2 "Somewhat Likely" 1 "Not Likely at all" 
label define e24_eng_ 3 "Very Likely" 2 "Somewhat Likely" 1 "Not Likely at all" 
label define e25_eng_ 3 "Very Likely" 2 "Somewhat Likely" 1 "Not Likely at all" 
label define e26_eng_ 3 "Very Likely" 2 "Somewhat Likely" 1 "Not Likely at all" 
label define e27_eng_ 3 "Very Likely" 2 "Somewhat Likely" 1 "Not Likely at all" 
label define e28_eng_ 3 "Very Likely" 2 "Somewhat Likely" 1 "Not Likely at all" 
label define e29_eng_ 3 "Very Likely" 2 "Somewhat Likely" 1 "Not Likely at all" 
label define e30_eng_ 3 "Very Likely" 2 "Somewhat Likely" 1 "Not Likely at all" 
label define rights_equity_1_ 1 "Agree" 2 "Disagree" 
label define rights_equity_2_ 1 "Agree" 2 "Disagree" 
label define rights_equity_3_ 1 "Agree" 2 "Disagree" 
label define rights_equity_4_ 1 "Agree" 2 "Disagree" 
label define rights_equity_5_ 1 "Agree" 2 "Disagree" 
label define rights_equity_6_ 1 "Agree" 2 "Disagree" 
label define rights_equity_7_ 1 "Agree" 2 "Disagree" 
label define rights_equity_8_ 1 "Agree" 2 "Disagree" 
label define rights_equity_9_ 1 "Agree" 2 "Disagree" 
label define rights_equity_10_ 1 "Agree" 2 "Disagree" 
label define rights_equity_11_ 1 "Agree" 2 "Disagree" 
label define rights_equity_12_ 1 "Agree" 2 "Disagree" 
label define rights_equity_13_ 1 "Agree" 2 "Disagree" 
label define rights_equity_14_ 1 "Agree" 2 "Disagree" 
label define gender_norms_1_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_2_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_3_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_4_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_5_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_6_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_7_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_8_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_9_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_10_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_11_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_12_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_13_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_14_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_15_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_16_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_norms_17_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_1_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_2_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_3_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_4_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_5_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_6_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_7_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_8_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_9_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_10_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_11_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_12_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_13_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_14_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_15_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_16_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_17_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_18_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_19_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_20_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_21_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_22_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_23_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define gender_role_24_ 0 "Do not agree at all" 1 "Somewhat agree" 2 "Agree a lot" 
label define masc_chronic_d1_ 1 "Not at all true" 2 "Somewhat true" 3 "Very true" 
label define masc_chronic_d2_ 1 "Not at all true" 2 "Somewhat true" 3 "Very true" 
label define masc_chronic_d3_ 1 "Not at all true" 2 "Somewhat true" 3 "Very true" 
label define masc_chronic_d4_ 1 "Not at all true" 2 "Somewhat true" 3 "Very true" 
label define masc_chronic_d5_ 1 "Not at all true" 2 "Somewhat true" 3 "Very true" 
label define masc_chronic_d6_ 1 "Not at all true" 2 "Somewhat true" 3 "Very true" 
label define masc_chronic_d7_ 1 "Not at all true" 2 "Somewhat true" 3 "Very true" 
label define masc_chronic_d8_ 1 "Not at all true" 2 "Somewhat true" 3 "Very true" 
label define masc_chronic_d9_ 1 "Not at all true" 2 "Somewhat true" 3 "Very true" 
label define c1_eng_ 3 "Often" 2 "Sometimes" 1 "Never" 98 "I dont know" 
label define c2_eng_ 3 "Often" 2 "Sometimes" 1 "Never" 98 "I dont know" 
label define c3_eng_ 3 "Often" 2 "Sometimes" 1 "Never" 98 "I dont know" 
label define c4_eng_ 1 "Yes" 0 "No" 98 "Dont Know" 
label define c4a_eng_ 3 "Almost every day (25 days or more)" 2 "Some days but not every day (more than 2 days but less than 25 days)" 1 "Only 1 or 2 days" 98 "Dont Know" 
label define c5_eng_ 1 "Yes" 0 "No" 98 "Dont Know" 
label define c6_eng_ 1 "Yes" 0 "No" 98 "Dont Know" 
label define c7_eng_ 1 "Yes" 0 "No" 98 "Dont Know" 
label define c8_eng_ 1 "Yes" 0 "No" 98 "Dont Know" 
label define c8a_eng_ 3 "Almost every day (25 days or more)" 2 "Some days but not every day (more than 2 days but less than 25 days)" 1 "Only 1 or 2 days" 98 "Dont Know" 
label define c_child_age_ 1 "Yes" 0 "No" 
label define c9_eng_ 3 "Often" 2 "Sometimes" 1 "Never" 98 "I dont know" 
label define c10_eng_ 3 "Often" 2 "Sometimes" 1 "Never" 98 "I dont know" 
label define c11_eng_ 3 "Often" 2 "Sometimes" 1 "Never" 98 "I dont know" 
label define c12_eng_ 1 "Yes" 0 "No" 98 "Dont Know" 
label define c13_eng_ 1 "Yes" 0 "No" 98 "Dont Know" 
label define c13a_eng_ 3 "Almost every day (25 days or more)" 2 "Some days but not every day (more than 2 days but less than 25 days)" 1 "Only 1 or 2 days" 98 "Dont Know" 
label define c14_eng_ 1 "Yes" 0 "No" 98 "Dont Know" 
label define c15_eng_ 1 "Yes" 0 "No" 98 "Dont Know" 
label define d1_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d2_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d3_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d4_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d5_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d6_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d7_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d8_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d9_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d10_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d11_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d12_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d13_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d14_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d15_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d16_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d17_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d18_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d19_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d20_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d21_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d22_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define d23_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define hiv_know1_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know2_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know3_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know4_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know5_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know6_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know7_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know8_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know9_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know10_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know11_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know12_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know13_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know14_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know15_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know16_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know17_ 1 "True" 2 "False" 3 "I dont know" 
label define hiv_know18_ 1 "True" 2 "False" 3 "I dont know" 
label define s5_q1_p_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s5_q2_p_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s5_q3_p_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s5_q4_p_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s5_q5_p_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s5_q6_p_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s5_q7_p_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s5_q8_p_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s5_q9_p_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s5_q10_p_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s5_q11_p_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s5_q12_p_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s5_q13_p_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s5_q14_p_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define tb_know1_ 1 "Agree" 2 "Disagree" 
label define tb_know2_ 1 "Agree" 2 "Disagree" 
label define tb_know3_ 1 "Agree" 2 "Disagree" 
label define tb_know4_ 1 "Agree" 2 "Disagree" 
label define tb_know5_ 1 "Agree" 2 "Disagree" 
label define tb_know6_ 1 "Agree" 2 "Disagree" 
label define tb_know7_ 1 "Agree" 2 "Disagree" 
label define tb_know8_ 1 "Agree" 2 "Disagree" 
label define tb_know9_ 1 "Agree" 2 "Disagree" 
label define tb_know10_ 1 "Agree" 2 "Disagree" 
label define tb_know11_ 1 "Agree" 2 "Disagree" 
label define s6_q1_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s6_q2_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s6_q3_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s6_q4_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s6_q5_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s6_q6_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s6_q7_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s6_q8_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s6_q9_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define s6_q10_ 3 "Strongly Agree" 2 "Agree" 1 "Disagree" 0 "Strongly Disagree" 
label define a1_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a2_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a3_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a4_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a5_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a6_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a7_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a8_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a9_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a10_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a11_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a12_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a17_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a29_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a30_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a31_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a32_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a33_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a34_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a35_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a36_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define a37_eng_ 1 "0 times" 2 "1-2 times" 3 "3-5 times" 4 "5-10 times" 5 "More than 10 times" 
label define a38_eng_ 1 "0 times" 2 "1-2 times" 3 "3-5 times" 4 "5-10 times" 5 "More than 10 times" 
label define a39_eng_ 1 "0 times" 2 "1-2 times" 3 "3-5 times" 4 "5-10 times" 5 "More than 10 times" 
label define a40_eng_ 1 "0 times" 2 "1-2 times" 3 "3-5 times" 4 "5-10 times" 5 "More than 10 times" 
label define a41_eng_ 1 "0 times" 2 "1-2 times" 3 "3-5 times" 4 "5-10 times" 5 "More than 10 times" 
label define a42_eng_ 1 "0 times" 2 "1-2 times" 3 "3-5 times" 4 "5-10 times" 5 "More than 10 times" 
label define a43_eng_ 1 "0 times" 2 "1-2 times" 3 "3-5 times" 4 "5-10 times" 5 "More than 10 times" 
label define a44_eng_ 1 "0 times" 2 "1-2 times" 3 "3-5 times" 4 "5-10 times" 5 "More than 10 times" 
label define b1_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b2_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b3_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b4_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b5_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b6_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b7_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b8_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b9_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b10_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b11_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b12_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b13_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b14_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b15_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b16_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b17_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b18_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b19_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b20_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b21_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b22_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b23_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b24_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b25_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b26_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b27_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b28_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b29_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b30_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b31_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define b32_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define maks1_ 1 "Strongly agree" 2 "Slightly agree" 3 "Neither agree nor disagree" 4 "Disagree slightly" 5 "Strongly disagree" 8 "Dont know" 
label define maks2_ 1 "Strongly agree" 2 "Slightly agree" 3 "Neither agree nor disagree" 4 "Disagree slightly" 5 "Strongly disagree" 8 "Dont know" 
label define maks3_ 1 "Strongly agree" 2 "Slightly agree" 3 "Neither agree nor disagree" 4 "Disagree slightly" 5 "Strongly disagree" 8 "Dont know" 
label define maks4_ 1 "Strongly agree" 2 "Slightly agree" 3 "Neither agree nor disagree" 4 "Disagree slightly" 5 "Strongly disagree" 8 "Dont know" 
label define maks5_ 1 "Strongly agree" 2 "Slightly agree" 3 "Neither agree nor disagree" 4 "Disagree slightly" 5 "Strongly disagree" 8 "Dont know" 
label define maks6_ 1 "Strongly agree" 2 "Slightly agree" 3 "Neither agree nor disagree" 4 "Disagree slightly" 5 "Strongly disagree" 8 "Dont know" 
label define maks7_ 1 "Strongly agree" 2 "Slightly agree" 3 "Neither agree nor disagree" 4 "Disagree slightly" 5 "Strongly disagree" 8 "Dont know" 
label define maks8_ 1 "Strongly agree" 2 "Slightly agree" 3 "Neither agree nor disagree" 4 "Disagree slightly" 5 "Strongly disagree" 8 "Dont know" 
label define maks9_ 1 "Strongly agree" 2 "Slightly agree" 3 "Neither agree nor disagree" 4 "Disagree slightly" 5 "Strongly disagree" 8 "Dont know" 
label define maks10_ 1 "Strongly agree" 2 "Slightly agree" 3 "Neither agree nor disagree" 4 "Disagree slightly" 5 "Strongly disagree" 8 "Dont know" 
label define maks11_ 1 "Strongly agree" 2 "Slightly agree" 3 "Neither agree nor disagree" 4 "Disagree slightly" 5 "Strongly disagree" 8 "Dont know" 
label define maks12_ 1 "Strongly agree" 2 "Slightly agree" 3 "Neither agree nor disagree" 4 "Disagree slightly" 5 "Strongly disagree" 8 "Dont know" 
label define bog_1_ 1 "Definitely not" 2 "Probably not" 3 "Probably" 4 "Definitely" 
label define bog_2_ 1 "Definitely not" 2 "Probably not" 3 "Probably" 4 "Definitely" 
label define bog_3_ 1 "Definitely not" 2 "Probably not" 3 "Probably" 4 "Definitely" 
label define bog_4_ 1 "Definitely not" 2 "Probably not" 3 "Probably" 4 "Definitely" 
label define bog_5_ 1 "Definitely not" 2 "Probably not" 3 "Probably" 4 "Definitely" 
label define bog_6_ 1 "Definitely not" 2 "Probably not" 3 "Probably" 4 "Definitely" 
label define pss1_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define pss2_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define pss3_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define pss4_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define pss5_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define pss6_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define pss7_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define pss8_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define pss9_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define pss10_eng_ 1 "Strongly Disagree" 2 "Disagree" 3 "Neither Disagree nor Agree" 4 "Agree" 5 "Strongly Agree" 
label define stig1_eng_ 1 "Untrue" 2 "Somewhat true" 3 "Very true" 99 "Unable to answer" 
label define stig2_eng_ 1 "Untrue" 2 "Somewhat true" 3 "Very true" 99 "Unable to answer" 
label define stig3_eng_ 1 "Untrue" 2 "Somewhat true" 3 "Very true" 99 "Unable to answer" 
label define stig4_eng_ 1 "Untrue" 2 "Somewhat true" 3 "Very true" 99 "Unable to answer" 
label define end_instruct_ 1 "Received" 
label define questionnaires_complete_ 0 "Incomplete" 1 "Unverified" 2 "Complete" 
label define is_the_participant_able_to_ 1 "Yes" 0 "No" 
label define proof_of_reimburseme_v_3_ 0 "Incomplete" 1 "Unverified" 2 "Complete" 
label define study_note_avail_ 1 "Yes" 0 "No" 
label define specify_the_seriousness_of_ 1 "N/A" 2 "Additional Information" 3 "Minor - no action required" 4 "Major - action required" 
label define the_study_note_is_addresse_ 1 "Project Coordinator (e.g. Liya and Brenda)" 2 "Project Manager (e.g. Dawie)" 3 "Study Data Administrator (e.g. Sphelele)" 4 "Data Manager (e.g. Freedom)" 5 "Principal Investigator (e.g. Andrew)" 
label define study_notes_complete_ 0 "Incomplete" 1 "Unverified" 2 "Complete" 
label define screening_and_consent_2_in_ 1 "Quality Control Check Completed" 
label define demo_qc_ 1 "Quality Control Check Completed" 
label define questionnaires_proof_of_sn_ 1 "Quality Control Check Completed" 
label define proof_of_snack_7_study_not_ 1 "Quality Control Check Completed" 
label define study_note_ 1 "Quality Control Check Completed" 
label define iqc_complete_ 0 "Incomplete" 1 "Unverified" 2 "Complete" 