label variable record_id "Record ID"
label variable oversampled "Record from oversampled square"
label variable ra_name_label "Research Assistant"
label variable labelling_date "Date:"
label variable labelling_time "Time:"
label variable ra_instruct "Instructions to the RA:  1. Please open your Community Map (with Square) on your tablet 2. Use the Community Map and Google Maps to         - Identify the Letter of the Square         - Determine which household to visit next 3. Make sure the household is within the Square 4. Locate the household 5. Use REDCap to guide you   YOU MUST CLICK ON CONTINUE BELOW"
label variable attempt "Household attempt number?"
label variable ra_instruct_1stattempt "Instruction to RA: Record/label the household number [record-name] on Google Maps App before continuing"
label variable google_map_pic "Please upload the picture you took from Google Maps as a proof that you visited the house."
label variable ra_instruct_2nd_3rdattempt "Instruction to RA:  This household number has already been labelled on Google Maps. DO NOT Record/Label household number [record-name] again! Please open Google Maps and check if household #[record-name] at has been labelled accurately "
label variable hhl_complete "Complete?"
label variable research_assistant_s_name_1 "Research Assistant"
label variable screening_date_1 "Screening Date"
label variable time_started_1 "Time Started"
label variable area_1 "Data collection site:"
label variable study_community_1 "Community Number:"
label variable square_number_1 "Square NUMBER: (This is the larger square)"
label variable sub_square_letter_1 "Square LETTER: (This is the smaller square)"
label variable confirm_infrontofgate_door_1 "Instruction to RA:Approach the door/gate of the Household"
label variable gps_coordinates_1 "GPS coordinates: Latitude"
label variable gps_coordinates_2_1 "GPS coordinates: Longitude"
label variable hhmember_present_1 "Was any household member present when you approached the household?"
label variable hh_not_present_confirm_1 "Please confirm that no household member was present"
label variable intro_script1_1 " INTRODUCTION SCRIPT FOR 1st CONTACT: ENGLISH Hello my name is __________________. Im a research assistant working for the Desmond Tutu Health Foundation (DTHF). DTHF with the support of Department of Health is working on various projects aimed at improving TB service provision in health facilities.  May I please speak with the head of the household?   INTRODUCTION SCRIPT FOR 1st CONTACT: isiXHOSA Molo igama lam ngu __________________. Ndingumncedisi wophando osebenzela iDesmond Tutu Health Foundation (DTHF) ngenkxaso yeSebe lezeMpilo isebenza kwiprojekti ezahlukeneyo ezijolise ekuphuculeni ubonelelo lwenkonzo zeTB kumaziko ezempilo. Ndicela ukuthetha nentloko yekhaya?   "
label variable hoh_at_home_1 "Is the Head of the Household currently at home?"
label variable intro_script_2_1 " INTRODUCTION SCRIPT FOR HoH: ENGLISH Hello my name is __________________. Im a research assistant working for the Desmond Tutu Health Foundation (DTHF). DTHF with the support of Department of Health is working on various projects aimed at improving TB service provision in health facilities. As a result
label variable interest_status_1 "Is the Head of the Household interested to participate?"
label variable research_assistant_s_name_2 "Research Assistant"
label variable screening_date_2 "Screening Date"
label variable time_started_2 "Time Started"
label variable area_2 "Data collection site:"
label variable study_community_2 "Community Number:"
label variable square_number_2 "Square NUMBER: (This is the larger square)"
label variable sub_square_letter_2 "Square LETTER: (This is the smaller square)"
label variable confirm_infrontofgate_door_2 "Instruction to RA:Approach the door/gate of the Household"
label variable gps_coordinates_2 "GPS coordinates: Latitude"
label variable gps_coordinates_2_2 "GPS coordinates: Longitude"
label variable hhmember_present_2 "Was any household member present when you approached the household?"
label variable hh_not_present_confirm_2 "Please confirm that no household member was present"
label variable intro_script1_2 " INTRODUCTION SCRIPT FOR 1st CONTACT: ENGLISH Hello my name is __________________. Im a research assistant working for the Desmond Tutu Health Foundation (DTHF). DTHF with the support of Department of Health is working on various projects aimed at improving TB service provision in health facilities.  May I please speak with the head of the household?   INTRODUCTION SCRIPT FOR 1st CONTACT: isiXHOSA Molo igama lam ngu __________________. Ndingumncedisi wophando osebenzela iDesmond Tutu Health Foundation (DTHF) ngenkxaso yeSebe lezeMpilo isebenza kwiprojekti ezahlukeneyo ezijolise ekuphuculeni ubonelelo lwenkonzo zeTB kumaziko ezempilo. Ndicela ukuthetha nentloko yekhaya?   "
label variable hoh_at_home_2 "Is the Head of the Household currently at home?"
label variable intro_script_2_2 " INTRODUCTION SCRIPT FOR HoH: ENGLISH Hello my name is __________________. Im a research assistant working for the Desmond Tutu Health Foundation (DTHF). DTHF with the support of Department of Health is working on various projects aimed at improving TB service provision in health facilities. As a result
label variable interest_status_2 "Is the Head of the Household interested to participate?"
label variable research_assistant_s_name_3 "Research Assistant"
label variable screening_date_3 "Screening Date"
label variable time_started_3 "Time Started"
label variable area_3 "Data collection site:"
label variable study_community_3 "Community Number:"
label variable square_number_3 "Square NUMBER: (This is the larger square)"
label variable sub_square_letter_3 "Square LETTER: (This is the smaller square)"
label variable confirm_infrontofgate_door_3 "Instruction to RA:Approach the door/gate of the Household"
label variable gps_coordinates_3 "GPS coordinates: Latitude"
label variable gps_coordinates_2_3 "GPS coordinates: Longitude"
label variable hhmember_present_3 "Was any household member present when you approached the household?"
label variable hh_not_present_confirm_3 "Please confirm that no household member was present"
label variable intro_script1_3 " INTRODUCTION SCRIPT FOR 1st CONTACT: ENGLISH Hello my name is __________________. Im a research assistant working for the Desmond Tutu Health Foundation (DTHF). DTHF with the support of Department of Health is working on various projects aimed at improving TB service provision in health facilities.  May I please speak with the head of the household?   INTRODUCTION SCRIPT FOR 1st CONTACT: isiXHOSA Molo igama lam ngu __________________. Ndingumncedisi wophando osebenzela iDesmond Tutu Health Foundation (DTHF) ngenkxaso yeSebe lezeMpilo isebenza kwiprojekti ezahlukeneyo ezijolise ekuphuculeni ubonelelo lwenkonzo zeTB kumaziko ezempilo. Ndicela ukuthetha nentloko yekhaya?   "
label variable hoh_at_home_3 "Is the Head of the Household currently at home?"
label variable intro_script_2_3 " INTRODUCTION SCRIPT FOR HoH: ENGLISH Hello my name is __________________. Im a research assistant working for the Desmond Tutu Health Foundation (DTHF). DTHF with the support of Department of Health is working on various projects aimed at improving TB service provision in health facilities. As a result
label variable interest_status_3 "Is the Head of the Household interested to participate?"
label variable screening_for_eligibility "Screening for EligibilityNote to RA: Please ask the following questions to the Head of the Household to assess whether they are eligible to partake in the study. Select Proceed  "
label variable how_old_are_you "How old are you?"
label variable calculated_age "Calculated Age  "
label variable participant_gender "Are you male or female?"
label variable lang_fluent "Are you fluent in either English or isiXhosa?"
label variable community "Does the HoH stay within the selected study square?"
label variable ra_the_participant_is_elig "RA: The participant is eligible to participate in the study
label variable ra_the_person_is_not_eligi "RA: The person is not eligible to participate in the study. This is the end of the screening and enrollment process. PLEASE THANK HIM/HER FOR THEIR TIME. Select End below as well as Unverified Save & Exit "
label variable note_to_ra_you_will_now_st "Note to RA: You will now start with the consenting process. Please make sure to do the following: 1. Select the most appropriate language below2. Read the consent form with the participant3. Allow for questions4. If willing to consent
label variable preferred_language_to_be_u "Preferred language to be used during the consenting process"
label variable did_the_person_consent_to "Did the person consent to participate in the TB Stigma Household Survey?"
label variable participant_can_sign "Can the participant sign for themselves?"
label variable consent_date "Consent Date "
label variable pin_setup1 "PIN SETUP"
label variable pin_setup2 "PIN SETUP 2"
label variable pin_setup3 "PIN SETUP 3"
label variable pin_setup4 "PIN SETUP 4"
label variable pin_setup5 "PIN SETUP 5"
label variable refconfirm "RA: The participant refused to provide consent to partake in the study.  This is the end of the screening and enrollment process. PLEASE THANK THE PARTICIPANT FOR HIS/HER TIME."
label variable consented_the_person_has_a "CONSENTED The person has agreed to provide consent. You will now obtain a unique PIN. This PIN will be generated by REDcap and should be used on all hard copy documents
label variable pin "FINAL PIN"
label variable pin_display "Participants PIN is:  [pin] "
label variable consent_qc_1 "1. Participant PIN is the same on all pages"
label variable consent_qc_2 "2. RA name written on the front page of the consent document"
label variable consent_qc_3 "3. RA signature and Date are written on the consent document"
label variable contact_no_2 "Specify the owner of this contact number."
label variable contact_owner_other "If other, please specify."
label variable timestamp_end_of_consent "Timestamp:"
label variable sc_complete "Complete?"
label variable demographics_date "Date of collecting demographics data"
label variable time_started_demographics "Time started"
label variable ra_name_7fd31b "Research Assistant's Name"
label variable language_prefer "Read the following out loud to the particpant: Im going to ask you questions before I ask you to complete the questionnaire on the tablet. Should I ask you the general questions in isiXhosa or English? Which do you prefer?"
label variable other_studies "Is anyone or has anyone in your household participated in any other TB-related research studies?"
label variable other_studies_time_e "When did this household member participate in a TB-related study?"
label variable s1_q1 "What is your race?"
label variable s1_q1_other "If other, please specify."
label variable place_of_birth_rsa_e "Were you born in South Africa?"
label variable place_of_birth_other "If other, please specify."
label variable specify_place_of_birth "Where were you born?"
label variable s1_q5 "What is your relationship status?"
label variable living_arrangement_e "Do you live together?"
label variable s1_q6 "What is the highest level of education that you have completed? "
label variable s1_q7 "What is your employment status?"
label variable s1_q14 "What is your total household income per month?"
label variable s2_q2 "Have you ever had TB in the past? "
label variable hoh_tb_hist_clinic "Which clinic did you go to for TB-care?   Yeyiphi ikliniki oye kuyo ukufumana ukhathalelo lwe-TB?  "
label variable hoh_tb_clinic_specify "Please specify: "
label variable hhm_tb_e "Has anyone in this household other than yourself had TB?"
label variable hhm_tb_hist_clinic "Which clinic did this person first go to for TB-care? Yeyiphi iklinikhi aqale waya kuyo lomntu ukuya kufuna ukhathalelo lwe-TB?"
label variable hhm_tb_clinic_specify "Please specify: "
label variable s2_q3 "Do you have a family member or friend outside of this household who has or has had TB?"
label variable s2_q5 "Have you been tested for HIV?"
label variable hh_member_hiv "Is anyone in this household living with HIV?"
label variable s2_q9 "Do you have a family member or friend
label variable s5_q1___1 "What do you think causes TB?RA Note: Participant should not be able to see answers (choice=I dont know)"
label variable s5_q1___2 "What do you think causes TB?RA Note: Participant should not be able to see answers (choice=Infection/Virus/Bacteria)"
label variable s5_q1___3 "What do you think causes TB?RA Note: Participant should not be able to see answers (choice=Witchcraft)"
label variable s5_q1___4 "What do you think causes TB?RA Note: Participant should not be able to see answers (choice=Infection from others)"
label variable s5_q1___5 "What do you think causes TB?RA Note: Participant should not be able to see answers (choice=Smoking)"
label variable s5_q1___6 "What do you think causes TB?RA Note: Participant should not be able to see answers (choice=Exposure to the cold)"
label variable s5_q1___7 "What do you think causes TB?RA Note: Participant should not be able to see answers (choice=Drinking alcohol)"
label variable s5_q1___8 "What do you think causes TB?RA Note: Participant should not be able to see answers (choice=Weak body)"
label variable s5_q1___9 "What do you think causes TB?RA Note: Participant should not be able to see answers (choice=Other
label variable s5_q1_other "If other, please specify"
label variable s5_q2___1 "How is TB spread from person to person?RA NOTE: Participant should not be able to see answers (choice=I dont know)"
label variable s5_q2___2 "How is TB spread from person to person?RA NOTE: Participant should not be able to see answers (choice=Physical contact (shaking hands
label variable s5_q2___3 "How is TB spread from person to person?RA NOTE: Participant should not be able to see answers (choice=Sharing foods/drinks/utensils)"
label variable s5_q2___4 "How is TB spread from person to person?RA NOTE: Participant should not be able to see answers (choice=Coughing/sneezing/talking/singing)"
label variable s5_q2___5 "How is TB spread from person to person?RA NOTE: Participant should not be able to see answers (choice=Poor sanitation/ sharing toilet seats)"
label variable s5_q2___6 "How is TB spread from person to person?RA NOTE: Participant should not be able to see answers (choice=Sex)"
label variable s5_q2___7 "How is TB spread from person to person?RA NOTE: Participant should not be able to see answers (choice=Other - Specify)"
label variable s5_q2_other "If other, please specify"
label variable s5_q3___1 "What are the signs and symptoms of TB? RA Note: Participant should not be able to see answers (choice=I dont know)"
label variable s5_q3___2 "What are the signs and symptoms of TB? RA Note: Participant should not be able to see answers (choice=Fever)"
label variable s5_q3___3 "What are the signs and symptoms of TB? RA Note: Participant should not be able to see answers (choice=Weight loss)"
label variable s5_q3___4 "What are the signs and symptoms of TB? RA Note: Participant should not be able to see answers (choice=Coughing)"
label variable s5_q3___5 "What are the signs and symptoms of TB? RA Note: Participant should not be able to see answers (choice=Night sweats)"
label variable s5_q3___6 "What are the signs and symptoms of TB? RA Note: Participant should not be able to see answers (choice=Coughing up blood)"
label variable s5_q3___7 "What are the signs and symptoms of TB? RA Note: Participant should not be able to see answers (choice=Loss of appetite)"
label variable s5_q3___8 "What are the signs and symptoms of TB? RA Note: Participant should not be able to see answers (choice=Chest pain)"
label variable s5_q3___9 "What are the signs and symptoms of TB? RA Note: Participant should not be able to see answers (choice=Breathlessness)"
label variable s5_q3___10 "What are the signs and symptoms of TB? RA Note: Participant should not be able to see answers (choice=Feeling weak)"
label variable s5_q3___11 "What are the signs and symptoms of TB? RA Note: Participant should not be able to see answers (choice=Other - Specify)"
label variable s5_q3_other "If other, please specify"
label variable s5_q4 "Can TB be cured?"
label variable s5_q5 "Does having HIV/AIDS increase the chances of developing TB?"
label variable mental_health_history_e___1 "Have you ever been diagnosed with a mental health disorder? (Select All that Apply)  (choice=Depression)"
label variable mental_health_history_e___2 "Have you ever been diagnosed with a mental health disorder? (Select All that Apply)  (choice=Anxiety)"
label variable mental_health_history_e___3 "Have you ever been diagnosed with a mental health disorder? (Select All that Apply)  (choice=PTSD)"
label variable mental_health_history_e___4 "Have you ever been diagnosed with a mental health disorder? (Select All that Apply)  (choice=Bipolar Disorder)"
label variable mental_health_history_e___5 "Have you ever been diagnosed with a mental health disorder? (Select All that Apply)  (choice=Epilepsy)"
label variable mental_health_history_e___6 "Have you ever been diagnosed with a mental health disorder? (Select All that Apply)  (choice=Panic)"
label variable mental_health_history_e___7 "Have you ever been diagnosed with a mental health disorder? (Select All that Apply)  (choice=Suicidality)"
label variable mental_health_history_e___8 "Have you ever been diagnosed with a mental health disorder? (Select All that Apply)  (choice=Alcohol/Substance abuse)"
label variable mental_health_history_e___9 "Have you ever been diagnosed with a mental health disorder? (Select All that Apply)  (choice=Schizophrenia)"
label variable mental_health_history_e___10 "Have you ever been diagnosed with a mental health disorder? (Select All that Apply)  (choice=Other)"
label variable mental_health_history_e___11 "Have you ever been diagnosed with a mental health disorder? (Select All that Apply)  (choice=None)"
label variable specify_disorder "If other, please specify"
label variable mental_health_history2_e "Have you ever received treatment for your mental disorder? "
label variable fam_mental_health1_e "Have you ever had any contact or ever cared for individuals with mental illness?  "
label variable fam_mental_health2_e "Do you have a family member or friend who has or has had mental illness?"
label variable total_hhm "Excluding yourself (participant)
label variable gender_hhm_1 "Gender of/ Isini se:Household member/ Lungu lekhaya #1"
label variable age_hhm_1 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #1"
label variable gender_hhm_2 "Gender of/Isini se : Household member/ Lungu lekhaya #2"
label variable age_hhm_2 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #2"
label variable gender_hhm_3 "Gender of/Isini se : Household member/ Lungu lekhaya #3"
label variable age_hhm_3 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #3"
label variable gender_hhm_4 "Gender of/Isini se: Household member/ Lungu lekhaya #4"
label variable age_hhm_4 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #4"
label variable gender_hhm_5 "Gender of/Isini se : Household member/ Lungu lekhaya #5"
label variable age_hhm_5 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #5"
label variable gender_hhm_6 "Gender of/Isini se : Household member/ Lungu lekhaya #6"
label variable age_hhm_6 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #6"
label variable gender_hhm_7 "Gender of/Isini se : Household member/ Lungu lekhaya #7"
label variable age_hhm_7 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #7"
label variable gender_hhm_8 "Gender of/Isini se : Household member/ Lungu lekhaya #8"
label variable age_hhm_8 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #8"
label variable gender_hhm_9 "Gender of/Isini se : Household member/ Lungu lekhaya #9"
label variable age_hhm_9 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #9"
label variable gender_hhm_10 "Gender of/Isini se : Household member/ Lungu lekhaya #10"
label variable age_hhm_10 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #10"
label variable gender_hhm_11 "Gender of/Isini se : Household member/ Lungu lekhaya #11"
label variable age_hhm_11 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #11"
label variable gender_hhm_12 "Gender of/Isini se : Household member/ Lungu lekhaya #12"
label variable age_hhm_12 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #12"
label variable gender_hhm_13 "Gender of/Isini se : Household member/ Lungu lekhaya #13"
label variable age_hhm_13 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #13"
label variable gender_hhm_14 "Gender of/Isini se : Household member/ Lungu lekhaya #14"
label variable age_hhm_14 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #14"
label variable gender_hhm_15 "Gender of/Isini se : Household member/ Lungu lekhaya #15"
label variable age_hhm_15 "Age of/ Minyaka ye:Household member/ Lungu lekhaya #15"
label variable age6to13_confirm "RA Instruction:Do NOT ASK the participant the following question. Check the list of household participants above and select the correct response below:"
label variable highest_education "What is the highest level of education you have completed?"
label variable highest_primary "What was the highest grade level you completed?"
label variable highest_grade_ofall "When considering ALL of the adults that live in the household
label variable highest_primary_ofall "What was the highest grade level completed? (When considering ALL of the adults that live in the household)"
label variable attend_school "Do the children aged between 6 and 13 go to school?"
label variable number_not_attending_school "How many children are not attending school?"
label variable highest_grade_notattending "What is the highest grade completed by the child/children not attending school?"
label variable child_mortality "Has anyone living in this household ever given birth to a boy or girl who was born alive but later died?"
label variable age_child_mortality "How old was the child when they died? "
label variable drinking_water_e "What is the main source of drinking water for members of your household?"
label variable drinking_water_specify_e "Please specify the main source of drinking water for members of your household:"
label variable water_located_e "Where is that water source located?"
label variable time_for_water "How long does it take to go there
label variable toilet_e "What kind of toilet facility do members of your household usually use?"
label variable fuel_e "What type of energy/fuel does your household mainly use for cooking?"
label variable fuel_specify_e "What type of energy/fuel does your household mainly use for cooking?"
label variable cooking_place_e "Is the cooking usually done in the house
label variable cooking_place_specify_e "Please specify where cooking is usually done:"
label variable seperate_cook_space_e "Please specify main energy/fuel used for cooking:"
label variable mains_elec_e "Does your household have electricity that is connected to the mains?"
label variable asset1 "A radio?"
label variable asset2 "A television?"
label variable asset3 "A landline telephone?"
label variable asset4 "A desktop or laptop computer?"
label variable asset5 "A refrigerator?"
label variable asset6 "A vacuum cleaner or floor polisher?"
label variable asset7 "A microwave oven?"
label variable asset8 "An electric or gas stove?"
label variable asset9 "A washing machine?"
label variable own1 "A watch?"
label variable own2 "A cell phone?"
label variable own3 "A bicycle?"
label variable own4 "A motorcycle or motor scooter?"
label variable own5 "An animal-drawn cart?"
label variable own6 "A car
label variable own7 "A boat with a motor?"
label variable floor "How would you describe the floor of your house?"
label variable floor_specify "Please specify floor of dwelling:"
label variable roof "How would you describe the roof of your house?"
label variable roof_specify "Please specify roof of dwelling:"
label variable fam_decision_1 "Who usually makes decisions about making major household purchases?"
label variable fam_decision_2 "Who usually makes decisions about making purchases for daily household needs?"
label variable fam_decision_3 "Who usually makes decisions about visits to family or relatives?"
label variable navigate_tablet_e "Are you able to navigate a tablet or smartphone?"
label variable ra_note_e "Note to RA:Please hand over the tablet to participant and ask him/her to read the following sentence OUT LOUD and click PROCEED when they are done. I had a cup of tea this morning and porridge for breakfast."
label variable literate_check_e "Was the participant able to read sentence on their own?"
label variable f1 "Soccer / football"
label variable f2 "Cooking"
label variable f3 "Spending time with family or friends"
label variable fun1___1 "Which of these foods do you eat? (choice=Rice)"
label variable fun1___2 "Which of these foods do you eat? (choice=Meat)"
label variable fun1___3 "Which of these foods do you eat? (choice=Pap)"
label variable fun1___4 "Which of these foods do you eat? (choice=Vegetables)"
label variable fun1___5 "Which of these foods do you eat? (choice=Fruit)"
label variable fun1___6 "Which of these foods do you eat? (choice=Other)"
label variable fun2 "If you could visit any country in the world
label variable instruct_part "DO NOT CLICK on the button below
label variable hhd_complete "Complete?"
label variable staff4 "Staff Name"
label variable date4 "Date"
label variable time4 "Start Time"
label variable ques_language "Note to RA:  Which language does the participant prefer to do the questionnaire in? "
label variable hoh_last_clinic_any_e "Which clinic did you last attend for any of your health needs?"
label variable symptom_preffered_clinic "If you had a cough
label variable tb_diagnosed_clinic_prefer "If you were diagnosed with TB
label variable hiv_clinic_prefer_test "If you were to get tested for HIV
label variable hiv_clinic_prefer_treat "If you were diagnosed with HIV
label variable non_tb_care_util "When was the last time you sought care for anything other than TB?"
label variable type_health_util___1 "In the past 2 years
label variable type_health_util___2 "In the past 2 years
label variable type_health_util___3 "In the past 2 years
label variable type_health_util___4 "In the past 2 years
label variable prison "Has anyone in this household ever spent time in jail or prison?"
label variable prison_time "How long did they spend in jail or prison?"
label variable prison_release "How long ago did they get released?"
label variable mines "Has anyone in this household ever work in the mines? "
label variable mines_time "How long did they spend working in the mines?"
label variable mines_long_ago "How long ago did they work in the mines?"
label variable ss1 "1. There is a special person who is around when I am in need."
label variable ss2 "2. There is a special person with whom I can share my joys and sorrows."
label variable ss3 "3. My family really tries to help me."
label variable ss4 "4. I get the emotional help and support I need from my family."
label variable ss5 "5. I have a special person who is a real source of comfort to me."
label variable ss6 "6. My friends really try to help me."
label variable ss7 "7. I can count on my friends when things go wrong."
label variable ss8 "8. I can talk about my problems with my family."
label variable ss9 "9. I have friends with whom I can share my joys and sorrows."
label variable ss10 "10. There is a special person in my life who cares about my feelings."
label variable ss11 "11. My family is willing to help me make decisions."
label variable ss12 "12. I can talk about my problems with my friends."
label variable e1_eng "People in the community where I live are friendly"
label variable e2_eng "People in the community where I live help each other without having to be asked"
label variable e3_eng "People in the community where I live trust their neighbors"
label variable e4_eng "How do you view other people?  Generally speaking
label variable e5_eng "People in the community where you live"
label variable e6_eng "People you work with"
label variable e7_eng "People at your church or place of worship"
label variable e8_eng "People who work in the stores where you shop"
label variable e9_eng "The local news sources
label variable e10_eng "Your online social network
label variable e11_eng "The police in your community"
label variable e12_eng "Xhosa people"
label variable e13_eng "Zulu people"
label variable e14_eng "Other Black South Africans
label variable e15_eng "Colored people"
label variable e16_eng "Indian people"
label variable e17_eng "White people"
label variable e18_eng "People who are from other African countries
label variable e21_eng "How likely is it that a neighbour would help you when you are sick?"
label variable e22_eng "How likely is it that you would help a neighbour when he/she is sick?"
label variable e23_eng "How likely is it that a neighbour would keep an eye on your home while you are away?"
label variable e24_eng "How likely is it that a neighbour would lend/borrow you R250?"
label variable e25_eng "How likely is it that you would lend a neighbour R250?"
label variable e26_eng "How likely is it that you would lend  a neighbor R60 to take public transportation?"
label variable e27_eng "How likely is it that a neighbour would lend/borrow you some salt?"
label variable e28_eng "How likely is it that you would lend a neighbour some salt?"
label variable e29_eng "Found and returned to you by someone who lives in the same community as you?"
label variable e30_eng "Found and returned to you by a complete stranger?"
label variable rights_equity_1 "It is important that sons have more education than daughters."
label variable rights_equity_2 "Daughters should be sent to school only if they are not needed to help at home."
label variable rights_equity_3 "The most important reason that sons should be more educated than daughters is so that they can better look after their parents when they are older."
label variable rights_equity_4 "If there is a limited amount of money to pay for tutoring
label variable rights_equity_5 "A woman should take good care of her own children and not worry about other peoples affairs."
label variable rights_equity_6 "Women should leave politics to the men."
label variable rights_equity_7 "A woman has to have a husband or sons or some other male kinsman to protect her."
label variable rights_equity_8 "The only thing a woman can really rely on in her old age is her sons."
label variable rights_equity_9 "A good woman never questions her husbands opinions
label variable rights_equity_10 "When it is a question of childrens health
label variable rights_equity_11 "Daughters should be able to work outside the home after they have children if they want to."
label variable rights_equity_12 "Daughters should have just the same chance to work outside the homes as sons."
label variable rights_equity_13 "Daughters should be told that an important reason not to have too many children is so they can work outside the home and earn money."
label variable rights_equity_14 "I would like my daughter to be able to work outside the home so she can support herself if necessary."
label variable gender_norms_1 "A women should tolerate violence to keep her family together."
label variable gender_norms_2 "If someone insults a man he should defend his reputation with force if he has to."
label variable gender_norms_3 "A man using violence against his wife is a private matter that shouldnt be discussed outside the couple."
label variable gender_norms_4 "It is the man who decides what type of sex to have."
label variable gender_norms_5 "Men are always ready to have sex."
label variable gender_norms_6 "Men need sex more than women do."
label variable gender_norms_7 "You dont talk about sex
label variable gender_norms_8 "A women who has sex before she marries does not deserve respect."
label variable gender_norms_9 "Women who carry condoms on them are easy."
label variable gender_norms_10 "It is a womans responsibility to avoid getting pregnant."
label variable gender_norms_11 "Only when a woman has a child is she a real woman."
label variable gender_norms_12 "A real man produces a male child."
label variable gender_norms_13 "Changing diapers
label variable gender_norms_14 "A womans role is taking care of her home and family."
label variable gender_norms_15 "The husband should decide to buy the major household items."
label variable gender_norms_16 "A man should have the final word about decisions in his home."
label variable gender_norms_17 "A woman should obey her husband in all things."
label variable gender_role_1 "I worry about failing and how it affects my doing well as a man"
label variable gender_role_2 "I am often concerned about how others evaluate my ability to provide for my family"
label variable gender_role_3 "I strive to be more successful than others."
label variable gender_role_4 "I sometimes define my personal value by my ability to make money or find work"
label variable gender_role_5 "Feeling that I am in good physical condition is important to me as a man"
label variable gender_role_6 "Being physically stronger than other men is important to me"
label variable gender_role_7 "I always strive to win in sports competitions."
label variable gender_role_8 "Having a girlfriend or wife is part of my idea of being a successful man"
label variable gender_role_9 "Making more money than woman is a measure of my value and personal worth"
label variable gender_role_10 "Being outperformed at work by a woman would make me uncomfortable"
label variable gender_role_11 "I would be concerned if my friends knew I lived with a woman and did any housework."
label variable gender_role_12 "I do not like to let woman take control of the situation"
label variable gender_role_13 "I would be concerned if my friends knew I stayed at home to take care of children while my wife goes to work."
label variable gender_role_14 "Having a female boss would be difficult for me"
label variable gender_role_15 "I have difficulty telling others I care about them"
label variable gender_role_16 "Talking about my feelings during or after sex is difficult for me"
label variable gender_role_17 "I often have trouble finding words to describe how I am feeling"
label variable gender_role_18 "I do not like to show my emotions to other people"
label variable gender_role_19 "Having someone see me cry would be difficult for me"
label variable gender_role_20 "Being able to perform sexually is important to me as a man"
label variable gender_role_21 "I feel that I always need to be ready for sex with my partner
label variable gender_role_22 "I worry about being unable to become sexually aroused when I want"
label variable gender_role_23 "It is important to me to now I can drink as much or more than others"
label variable gender_role_24 "Having sex is part of being a successful man"
label variable masc_chronic_d1 "Being physically strong is important to me"
label variable masc_chronic_d2 "I like to know I am looking after my partner or family"
label variable masc_chronic_d3 "Having a good level of fitness is important to me"
label variable masc_chronic_d4 "I am a fighter"
label variable masc_chronic_d5 "I need to provide financial security for my partner or family"
label variable masc_chronic_d6 "Being an active person in important to me"
label variable masc_chronic_d7 "Being able to provide for my partner or family is important to me"
label variable masc_chronic_d8 "I am a competitive person"
label variable masc_chronic_d9 "Its up to me to protect my partner or family"
label variable c1_eng "1. We worried whether our food would run out before we could get more or get money to buy more.   Did this happen often
label variable c2_eng "2. The food that we had just didnt last
label variable c3_eng "3. We were not able get or afford healthy meals. Did this happen often
label variable c4_eng "4. In the last 30 days
label variable c4a_eng "4a. How often did this happen -- almost every day
label variable c5_eng "5. In the last 30 days
label variable c6_eng "6. In the last 30 days
label variable c7_eng "7. In the last 30 days
label variable c8_eng "8. In the last 30 days
label variable c8a_eng "8a. [If Yes to above] How often did this happen --almost every day
label variable c_child_age "Do you have a child who is less than 18 years of age in your household?"
label variable c9_eng "9. We relied on only a few kinds of low-cost food to feed the children because we couldnt get or afford more food.   Did this happen often
label variable c10_eng "10. We couldnt feed the children a healthy meal
label variable c11_eng "11. The children in our household were not eating enough because we just couldnt get or afford enough food.   Did this happen often
label variable c12_eng "12. In the last 30 days
label variable c13_eng "13. In the last 30 days
label variable c13a_eng "13a. How often did this happen -- almost every day
label variable c14_eng "14. In the last 30 days
label variable c15_eng "15. In the last 30 days
label variable d1_eng "1.Poor people are poor because they lack the ability to manage money"
label variable d2_eng "2.Poor people are poor because they waste their money on inappropriate items"
label variable d3_eng "3.Poor people are poor because they do not actively seek to improve their lives"
label variable d4_eng "4.Poor people are poor because they do not really want to work"
label variable d5_eng "5.Poor people are poor because they do not make a sufficient effort to find work"
label variable d6_eng "6.Poor people are poor because they lack sufficient self motivation"
label variable d7_eng "7.Poor people are poor because they prefer to have others take care of them"
label variable d8_eng "8.Poor people are poor because they do not take enough responsibility for themselves"
label variable d9_eng "9.Poor people are poor because they are exploited by rich people"
label variable d10_eng "10.Poor people are poor because society is not fair"
label variable d11_eng "11.Poor people are poor because the wealth in society is not equally distributed"
label variable d12_eng "12.Poor people are poor because they lack opportunities because they live in poor families"
label variable d13_eng "13.Poor people are poor because the government does not help people in economic difficulties"
label variable d14_eng "14.Poor people are poor because of their social situation"
label variable d15_eng "15.Poor people are poor because of the historical groups (e.g. Race
label variable d16_eng "16.Poor people are poor because of social things"
label variable d17_eng "17.Poor people are poor because society does not provide the basic needs (eg. Food
label variable d18_eng "18.Poor people are poor because society fails to create sufficient jobs"
label variable d19_eng "19.Poor people are poor because they were meant to be poor"
label variable d20_eng "20.Poor people are poor because they lack luck"
label variable d21_eng "21.Poor people are poor because they have experienced difficulties"
label variable d22_eng "22.Poor people are poor because they are not motivated because they receive social grants"
label variable d23_eng "23.Poor people are poor because they were born less important than others"
label variable hiv_know1 "Coughing and sneezing DO NOT spread HIV"
label variable hiv_know2 "A person can get HIV by sharing a glass of water with someone who has HIV"
label variable hiv_know3 "Pulling out the penis before a man climaxes/cums keeps a woman from getting HIV during sex"
label variable hiv_know4 "A woman can get HIV if she has anal sex with a man"
label variable hiv_know5 "Showering
label variable hiv_know6 "All pregnant women infected with HIV will have babies born with AIDS"
label variable hiv_know7 "People who have been infected with HIV quickly show serious signs of being infected"
label variable hiv_know8 "There is a vaccine that can stop adults from getting HIV"
label variable hiv_know9 "People are likely to get HIV by deep kissing
label variable hiv_know10 "A woman cannot get HIV if she has sex during her period"
label variable hiv_know11 "There is a female condom that can help decrease a womans chance of getting HIV"
label variable hiv_know12 "A natural skin condom works better against HIV than does a latex condom"
label variable hiv_know13 "A person will NOT get HIV if she or he is taking antibiotics"
label variable hiv_know14 "Having sex with more than one partner can increase a persons chance of being infected with HIV"
label variable hiv_know15 "Taking a test for HIV one week after having sex will tell a person if she or he has HIV"
label variable hiv_know16 "A person can get HIV by sitting in a hot tub or a swimming pool with a person who has HIV"
label variable hiv_know17 "A person can get HIV from oral sex"
label variable hiv_know18 "Using vaseline or baby oil with condoms lowers the chance of getting HIV"
label variable s5_q1_p "Most people think that getting HIV is a punishment for bad behaviour"
label variable s5_q2_p "Most people think that having HIV is just a matter of bad luck"
label variable s5_q3_p "Most people think less of someone because they have HIV"
label variable s5_q4_p "Most people would not like someone with HIV to be living next door"
label variable s5_q5_p "Most people would reject the friendship of someone with HIV"
label variable s5_q6_p "Most people feel that it is safe for a person with HIV to look after somebody elses children"
label variable s5_q7_p "Most people would not date a person if they know that he/she has HIV"
label variable s5_q8_p "Most people are afraid to be around people with HIV"
label variable s5_q9_p "Most people feel that if you have HIV it is your own fault"
label variable s5_q10_p "Most employers would not hire someone with HIV to work for them"
label variable s5_q11_p "Most people would not drink from a tap if a person with HIV had just drunk from it"
label variable s5_q12_p "Most people believe that if you have HIV you must have done something wrong to deserve it"
label variable s5_q13_p "Most people believe that someone with HIV should be ashamed of themselves"
label variable s5_q14_p "Most people feel uncomfortable around people with HIV"
label variable tb_know1 "TB is a communicable disease"
label variable tb_know2 "TB is hereditary"
label variable tb_know3 "TB is caused by a germ"
label variable tb_know4 "TB is spread by droplets through cough and sneeze"
label variable tb_know5 "There are effective drugs to treat TB"
label variable tb_know6 "Anti-TB drugs should be given for 6-8 months"
label variable tb_know7 "Anti-TB drugs can be skipped for a day or two"
label variable tb_know8 "TB can cause death"
label variable tb_know9 "TB drugs should be discontinued if patient starts feeling better"
label variable tb_know10 "HIV patients have a higher chance of developing TB"
label variable tb_know11 "Failure to take medicine can yield to more serious forms of TB"
label variable s6_q1 "People may not want to eat or drink with friends who have TB"
label variable s6_q2 "People may not want to eat or drink with relatives who have TB"
label variable s6_q3 "People feel uncomfortable about being near those with TB"
label variable s6_q4 "If a person has TB
label variable s6_q5 "People do not want those with TB playing with their children"
label variable s6_q6 "People keep their distance from people with TB"
label variable s6_q7 "People do not want to talk to others with TB"
label variable s6_q8 "People are afraid of those with TB"
label variable s6_q9 "People try not to touch others with TB"
label variable s6_q10 "People prefer not to have those with TB living in their community"
label variable a1_eng "1. People in the community where I live feel like they belong  to the community"
label variable a2_eng "2. People in the community where I live are committed to  the well-being of the community."
label variable a3_eng "3. People in the community where I live have hope about the future."
label variable a4_eng "4. People in the community where I live help each other."
label variable a5_eng "5. The community where I live treats people fairly no matter  what their background is."
label variable a6_eng "6. The community where I live supports programs for           children and families."
label variable a7_eng "7. People in the community where I live work together to improve the community."
label variable a8_eng "8. People in the community where I live can be trusted."
label variable a9_eng "9. The community where I live has the resources it needs to take care of problems in the community (Resources may include money
label variable a10_eng "10. People in the community where I live are able to get the  services they need."
label variable a11_eng "11. People in the community where I live know where to go to get things done."
label variable a12_eng "12. The community where I live works with different people and groups outside the community to get things done."
label variable a17_eng "17. The community where I live has effective leaders."
label variable a29_eng "1. People in the community where I live care about each other."
label variable a30_eng "2. The community where I live is a safe place to live and  work."
label variable a31_eng "3. Good housing is available for people who live in the community where I live."
label variable a32_eng "4. People in the community where I live can access necessary health care services."
label variable a33_eng "5. Good educational opportunities are available to people who live in the community where I live."
label variable a34_eng "6. Good work opportunities  are available to people who live in the community where I live."
label variable a35_eng "7. People in the community where I live have friendships with their neighbors."
label variable a36_eng "8. People in the community where I live have opportunities to become leaders in the community or in local organizations"
label variable a37_eng "1. Spoken to your neighbors?"
label variable a38_eng "2. Helped a neighbor or received help from a neighbor?"
label variable a39_eng "3. Had neighbors in your home or been in their home?"
label variable a40_eng "4. Attended a public meeting in which there was a discussion of local community affairs? "
label variable a41_eng "5. Attended any organization meetings (who implement community initiatives)?"
label variable a42_eng "6. Attended community events?"
label variable a43_eng "7. Volunteered for community initiatives?"
label variable a44_eng "8. Obtained [or got?] information from local news sources? "
label variable b1_eng "1.People with depression could stop being depressed if they wanted."
label variable b2_eng "2.Depression is a sign of weakness."
label variable b3_eng "3.Depression is not a real medical illness."
label variable b4_eng "4.People with depression are dangerous."
label variable b5_eng "5.It is best to avoid people with depression so you dont become depressed yourself."
label variable b6_eng "6.People with depression are lazy."
label variable b7_eng "7.If I had depression I would not tell anyone."
label variable b8_eng "8.I would not employ someone if I knew they had been depressed."
label variable b9_eng "9.I would not vote for a politician if I knew they had been depressed."
label variable b10_eng "10.People who abuse alcohol could stop if they wanted."
label variable b11_eng "11.Alcohol abuse is a sign of weakness."
label variable b12_eng "12.Alcohol abuse is not a real medical illness."
label variable b13_eng "13.People who abuse alcohol are dangerous."
label variable b14_eng "14.It is best to avoid people who abuse alcohol so you dont start abusing alcohol yourself."
label variable b15_eng "15.People who abuse alcohol are lazy."
label variable b16_eng "16.If I abused alcohol I would not tell anyone"
label variable b17_eng "17.I would not employ someone if I knew they had previously abused alcohol."
label variable b18_eng "18.I would not vote for a politician if I knew they had previously abused alcohol."
label variable b19_eng "19.People who abuse drugs could stop if they wanted."
label variable b20_eng "20.Drug abuse is a sign of weakness."
label variable b21_eng "21.Drug abuse is not a real medical illness"
label variable b22_eng "22.People who abuse drugs are dangerous."
label variable b23_eng "23.It is best to avoid people who abuse drug so you dont start abusing drugs yourself."
label variable b24_eng "24.People who abuse drugs are lazy."
label variable b25_eng "25.If I abused drugs I would not tell anyone."
label variable b26_eng "26.I would not employ someone if I knew they had previously abused drugs."
label variable b27_eng "27.I would not vote for a politician if I knew they had previously abused drugs."
label variable b28_eng "28.People who have TB  and drink alcohol should be ashamed of themselves."
label variable b29_eng "29. People who have TB and stop drinking alcohol are more responsible."
label variable b30_eng "30. People who have TB should not be allowed to drink alcohol."
label variable b31_eng "31.The nurses at the clinic should reprimand people who have TB and drink alcohol."
label variable b32_eng "32. People who drink alcohol should not be allowed to take their TB medication."
label variable maks1 "1. Most people with mental health problems want to have paid employment"
label variable maks2 "2,  If a friend had a mental health problem, I know what advice to give them to get professional help."
label variable maks3 "3. Medication can be an effective treatment for people with mental health problems"
label variable maks4 "4. Psychotherapy (for example
label variable maks5 "5. People with severe mental health problems can fully recover"
label variable maks6 "6. Most people with mental health problems go to a health care professional to get help"
label variable maks7 "7. Depression"
label variable maks8 "8. Stress"
label variable maks9 "9. Schizophrenia"
label variable maks10 "10. Bipolar disorder (manic depression)"
label variable maks11 "11. Drug addition"
label variable maks12 "12. Grief"
label variable bog_1 "1. Would you be ashamed if people knew someone in your family has/ has had mental illness?"
label variable bog_2 "2. Would you have a conversation with someone with mental illness without fear?"
label variable bog_3 "3. Would you work on the same job with someone with mental illness?"
label variable bog_4 "4. Would you maintain friendship with someone with mental illness?"
label variable bog_5 "5. Would you share a room with someone with mental illness?"
label variable bog_6 "6. Would you marry someone with mental illness?"
label variable pss1_eng "1. Most people infected with COVID-19 do not take care of their health."
label variable pss2_eng "2. Most people infected with COVID-19 do not follow expert medical advice."
label variable pss3_eng "3. Most people infected with COVID-19 like to party or socialise often."
label variable pss4_eng "4. Most people infected with COVID-19 are contaminated with germs."
label variable pss5_eng "5. Most people infected with COVID-19 are a burden to their families and society."
label variable pss6_eng "6. Most people infected with COVID-19 are socially irresponsible."
label variable pss7_eng "7. Most people infected with COVID-19 are a danger to other people."
label variable pss8_eng "8. I fear people infected with COVID-19."
label variable pss9_eng "9.  I fear people who are at risk of COVID-19 infection even if they have not been infected yet."
label variable pss10_eng "10. I fear being infected with COVID-19 if I live in a community with people who are infected with COVID-19."
label variable stig1_eng "11. People are afraid of a person who has had coronavirus/COVID-19?"
label variable stig2_eng "12. People are afraid of a person who has recovered from coronavirus/COVID-19?"
label variable stig3_eng "13. People are afraid of a person if they have family who had coronavirus/COVID-19?"
label variable stig4_eng "14. People are afraid of healthcare providers who provide care for patients with coronavirus/COVID-19?"
label variable end_instruct " Research Assistant: Please check all items in the questionnaire to ensure the participant completed all the questions. Please click on Received button below once the participant handed back the tablet. "
label variable end_time "Questionnaire/s end time:"
label variable questionnaires_complete "Complete?"
label variable ra_name2 "Staff Name"
label variable date2 "Date"
label variable snack_time "Time Started"
label variable voucher "Please insert the voucher number here:"
label variable is_the_participant_able_to "Is the participant able to sign without the assistance of a witness?"
label variable sig_reimburs "I, [pin], hereby confirm that I have been given snacks and a R50 voucher by a DTHF staff member as part of my participation in the TB Stigma Household Survey study."
label variable sign_withn "I sign on behalf of, [pin], confirming that snacks and a R50 voucher was given by a DTHF staff member as part of participation in the TB Stigma Household Survey study."
label variable please_specify_the_name_an "Please specify the name and surname of the witness."
label variable additional_notes3 "Notes"
label variable prs_complete "Complete?"
label variable ra_name_1 "Staff Name"
label variable date_1 "Date"
label variable start_time_2_1 "Time Started "
label variable study_note_avail_1 "Are there study note that you would like to record for this participant? "
label variable briefly_specify_the_nature_1 "Include study notes here: "
label variable specify_the_seriousness_of_1 "Specify the seriousness of the event"
label variable the_study_note_is_addresse_1 "The study note is addressed to the following person"
label variable study_notes_complete_1 "Complete?"
label variable additional_notes_1 "Additional Notes"
label variable ra_name_1 "Staff Name"
label variable date_1 "Date"
label variable start_time_2_1 "Time Started "
label variable study_note_avail_1 "Are there study note that you would like to record for this participant? "
label variable briefly_specify_the_nature_2 "Include study notes here: "
label variable specify_the_seriousness_of_1 "Specify the seriousness of the event"
label variable the_study_note_is_addresse_1 "The study note is addressed to the following person"
label variable additional_notes_2 "Additional Notes"
label variable study_notes_complete_2 "Complete?"
label variable ra_name_3 "Staff Name"
label variable date_3 "Date"
label variable start_time_2_3 "Time Started "
label variable study_note_avail_3 "Are there study note that you would like to record for this participant? "
label variable briefly_specify_the_nature_3 "Include study notes here: "
label variable specify_the_seriousness_of_3 "Specify the seriousness of the event"
label variable the_study_note_is_addresse_3 "The study note is addressed to the following person"
label variable additional_notes_3 "Additional Notes"
label variable study_notes_complete_3 "Complete?"
label variable ra_name3 "Staff Name"
label variable date3 "Date"
label variable timestamp_start_of_qc "Time started"
label variable screening_and_consent_2_in "1. Screening and Consenting"
label variable demo_qc "2. Demographics"
label variable questionnaires_proof_of_sn "3. Questionnaires"
label variable proof_of_snack_7_study_not "4. Proof of Reimbursement and Snack"
label variable study_note "5. Study Note"
label variable timestamp_end_qc "Time ended"
label variable additional_notes4 "Additional Notes"
label variable iqc_complete "Complete?"
